version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: django
    versions:
    - ">= 2.a, < 3"
  - dependency-name: django
    versions:
    - ">= 3.a, < 4"
  - dependency-name: djangorestframework
    versions:
    - "> 3.9.4, < 4"
  - dependency-name: nltk
    versions:
    - 3.6.1
  - dependency-name: elasticsearch
    versions:
    - 7.11.0
    - 7.12.0
  - dependency-name: tox
    versions:
    - 3.22.0
    - 3.23.0
  - dependency-name: backports-functools-lru-cache
    versions:
    - 1.6.3
  - dependency-name: protobuf
    versions:
    - 3.15.2
    - 3.15.3
    - 3.15.6
  - dependency-name: tlds
    versions:
    - "2021020300"
    - "2021030700"
    - "2021030802"
    - "2021031000"
  - dependency-name: pillow
    versions:
    - 8.1.1
  - dependency-name: numpy
    versions:
    - 1.20.0
    - 1.20.1
  - dependency-name: django-q
    versions:
    - 1.3.4
  - dependency-name: unidecode
    versions:
    - 1.1.2
