# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-15 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dir', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domaininfo',
            name='last_updated',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
