# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-16 00:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dir', '0003_auto_20210215_0234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domaininfo',
            name='blocked_to_crawled_ratio',
        ),
        migrations.RemoveField(
            model_name='domaininfo',
            name='max_urls',
        ),
        migrations.RemoveField(
            model_name='domaininfo',
            name='only_crawl_rooturl',
        ),
    ]
