# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-16 00:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dir', '0004_auto_20210215_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockedsite',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
