# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-16 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dir', '0006_auto_20210215_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badquery',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='domainsuffix',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='favicon',
            name='date_taken',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='indexstats',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='indexstats',
            name='last_most_linked_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ipaddress',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ipaddress',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='monthlysearchreport',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='screenshot',
            name='date_taken',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
