# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dir', '0016_auto_20160317_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultClick',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('keywords', models.TextField()),
                ('search_id', models.IntegerField()),
                ('position', models.IntegerField()),
                ('ip', models.CharField(unique=True, max_length=16)),
                ('url', models.TextField(db_index=True)),
                ('click_time', models.DateTimeField(auto_now_add=True)),
                ('xpos', models.IntegerField(null=True, blank=True)),
                ('ypos', models.IntegerField(null=True, blank=True)),
            ],
            options={
                'abstract': False,
                'in_db': 'indexes',
            },
        ),
        migrations.CreateModel(
            name='ResultClick_af',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('keywords', models.TextField()),
                ('search_id', models.IntegerField()),
                ('position', models.IntegerField()),
                ('ip', models.CharField(unique=True, max_length=16)),
                ('url', models.TextField(db_index=True)),
                ('click_time', models.DateTimeField(auto_now_add=True)),
                ('xpos', models.IntegerField(null=True, blank=True)),
                ('ypos', models.IntegerField(null=True, blank=True)),
            ],
            options={
                'abstract': False,
                'in_db': 'indexes',
            },
        ),
        migrations.CreateModel(
            name='ResultClick_ak',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('keywords', models.TextField()),
                ('search_id', models.IntegerField()),
                ('position', models.IntegerField()),
                ('ip', models.CharField(unique=True, max_length=16)),
                ('url', models.TextField(db_index=True)),
                ('click_time', models.DateTimeField(auto_now_add=True)),
                ('xpos', models.IntegerField(null=True, blank=True)),
                ('ypos', models.IntegerField(null=True, blank=True)),
            ],
            options={
                'abstract': False,
                'in_db': 'indexes',
            },
        ),
        migrations.CreateModel(
            name='ResultClick_bm',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('keywords', models.TextField()),
                ('search_id', models.IntegerField()),
                ('position', models.IntegerField()),
                ('ip', models.CharField(unique=True, max_length=16)),
                ('url', models.TextField(db_index=True)),
                ('click_time', models.DateTimeField(auto_now_add=True)),
                ('xpos', models.IntegerField(null=True, blank=True)),
                ('ypos', models.IntegerField(null=True, blank=True)),
            ],
            options={
                'abstract': False,
                'in_db': 'indexes',
            },
        ),
        migrations.CreateModel(
            name='ResultClick_br',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('keywords', models.TextField()),
                ('search_id', models.IntegerField()),
                ('position', models.IntegerField()),
                ('ip', models.CharField(unique=True, max_length=16)),
                ('url', models.TextField(db_index=True)),
                ('click_time', models.DateTimeField(auto_now_add=True)),
                ('xpos', models.IntegerField(null=True, blank=True)),
                ('ypos', models.IntegerField(null=True, blank=True)),
            ],
            options={
                'abstract': False,
                'in_db': 'indexes',
            },
        ),
        migrations.CreateModel(
            name='ResultClick_ca',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('keywords', models.TextField()),
                ('search_id', models.IntegerField()),
                ('position', models.IntegerField()),
                ('ip', models.CharField(unique=True, max_length=16)),
                ('url', models.TextField(db_index=True)),
                ('click_time', models.DateTimeField(auto_now_add=True)),
                ('xpos', models.IntegerField(null=True, blank=True)),
                ('ypos', models.IntegerField(null=True, blank=True)),
            ],
            options={
                'abstract': False,
                'in_db': 'indexes',
            },
        ),
        migrations.CreateModel(
            name='ResultClick_cs',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('keywords', models.TextField()),
                ('search_id', models.IntegerField()),
                ('position', models.IntegerField()),
                ('ip', models.CharField(unique=True, max_length=16)),
                ('url', models.TextField(db_index=True)),
                ('click_time', models.DateTimeField(auto_now_add=True)),
                ('xpos', models.IntegerField(null=True, blank=True)),
                ('ypos', models.IntegerField(null=True, blank=True)),
            ],
            options={
                'abstract': False,
                'in_db': 'indexes',
            },
        ),
        migrations.CreateModel(
            name='ResultClick_cy',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('keywords', models.TextField()),
                ('search_id', models.IntegerField()),
                ('position', models.IntegerField()),
                ('ip', models.CharField(unique=True, max_length=16)),
                ('url', models.TextField(db_index=True)),
                ('click_time', models.DateTimeField(auto_now_add=True)),
                ('xpos', models.IntegerField(null=True, blank=True)),
                ('ypos', models.IntegerField(null=True, blank=True)),
            ],
            options={
                'abstract': False,
                'in_db': 'indexes',
            },
        ),
        migrations.CreateModel(
            name='ResultClick_da',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('keywords', models.TextField()),
                ('search_id', models.IntegerField()),
                ('position', models.IntegerField()),
                ('ip', models.CharField(unique=True, max_length=16)),
                ('url', models.TextField(db_index=True)),
                ('click_time', models.DateTimeField(auto_now_add=True)),
                ('xpos', models.IntegerField(null=True, blank=True)),
                ('ypos', models.IntegerField(null=True, blank=True)),
            ],
            options={
                'abstract': False,
                'in_db': 'indexes',
            },
        ),
        migrations.CreateModel(
            name='ResultClick_de',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('keywords', models.TextField()),
                ('search_id', models.IntegerField()),
                ('position', models.IntegerField()),
                ('ip', models.CharField(unique=True, max_length=16)),
                ('url', models.TextField(db_index=True)),
                ('click_time', models.DateTimeField(auto_now_add=True)),
                ('xpos', models.IntegerField(null=True, blank=True)),
                ('ypos', models.IntegerField(null=True, blank=True)),
            ],
            options={
                'abstract': False,
                'in_db': 'indexes',
            },
        ),
        migrations.CreateModel(
            name='ResultClick_ee',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('keywords', models.TextField()),
                ('search_id', models.IntegerField()),
                ('position', models.IntegerField()),
                ('ip', models.CharField(unique=True, max_length=16)),
                ('url', models.TextField(db_index=True)),
                ('click_time', models.DateTimeField(auto_now_add=True)),
                ('xpos', models.IntegerField(null=True, blank=True)),
                ('ypos', models.IntegerField(null=True, blank=True)),
            ],
            options={
                'abstract': False,
                'in_db': 'indexes',
            },
        ),
        migrations.CreateModel(
            name='ResultClick_el',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('keywords', models.TextField()),
                ('search_id', models.IntegerField()),
                ('position', models.IntegerField()),
                ('ip', models.CharField(unique=True, max_length=16)),
                ('url', models.TextField(db_index=True)),
                ('click_time', models.DateTimeField(auto_now_add=True)),
                ('xpos', models.IntegerField(null=True, blank=True)),
                ('ypos', models.IntegerField(null=True, blank=True)),
            ],
            options={
                'abstract': False,
                'in_db': 'indexes',
            },
        ),
        migrations.CreateModel(
            name='ResultClick_eo',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('keywords', models.TextField()),
                ('search_id', models.IntegerField()),
                ('position', models.IntegerField()),
                ('ip', models.CharField(unique=True, max_length=16)),
                ('url', models.TextField(db_index=True)),
                ('click_time', models.DateTimeField(auto_now_add=True)),
                ('xpos', models.IntegerField(null=True, blank=True)),
                ('ypos', models.IntegerField(null=True, blank=True)),
            ],
            options={
                'abstract': False,
                'in_db': 'indexes',
            },
        ),
        migrations.CreateModel(
            name='ResultClick_es',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('keywords', models.TextField()),
                ('search_id', models.IntegerField()),
                ('position', models.IntegerField()),
                ('ip', models.CharField(unique=True, max_length=16)),
                ('url', models.TextField(db_index=True)),
                ('click_time', models.DateTimeField(auto_now_add=True)),
                ('xpos', models.IntegerField(null=True, blank=True)),
                ('ypos', models.IntegerField(null=True, blank=True)),
            ],
            options={
                'abstract': False,
                'in_db': 'indexes',
            },
        ),
        migrations.CreateModel(
            name='ResultClick_et',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('keywords', models.TextField()),
                ('search_id', models.IntegerField()),
                ('position', models.IntegerField()),
                ('ip', models.CharField(unique=True, max_length=16)),
                ('url', models.TextField(db_index=True)),
                ('click_time', models.DateTimeField(auto_now_add=True)),
                ('xpos', models.IntegerField(null=True, blank=True)),
                ('ypos', models.IntegerField(null=True, blank=True)),
            ],
            options={
                'abstract': False,
                'in_db': 'indexes',
            },
        ),
        migrations.CreateModel(
            name='ResultClick_eu',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('keywords', models.TextField()),
                ('search_id', models.IntegerField()),
                ('position', models.IntegerField()),
                ('ip', models.CharField(unique=True, max_length=16)),
                ('url', models.TextField(db_index=True)),
                ('click_time', models.DateTimeField(auto_now_add=True)),
                ('xpos', models.IntegerField(null=True, blank=True)),
                ('ypos', models.IntegerField(null=True, blank=True)),
            ],
            options={
                'abstract': False,
                'in_db': 'indexes',
            },
        ),
        migrations.CreateModel(
            name='ResultClick_ff',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('keywords', models.TextField()),
                ('search_id', models.IntegerField()),
                ('position', models.IntegerField()),
                ('ip', models.CharField(unique=True, max_length=16)),
                ('url', models.TextField(db_index=True)),
                ('click_time', models.DateTimeField(auto_now_add=True)),
                ('xpos', models.IntegerField(null=True, blank=True)),
                ('ypos', models.IntegerField(null=True, blank=True)),
            ],
            options={
                'abstract': False,
                'in_db': 'indexes',
            },
        ),
        migrations.CreateModel(
            name='ResultClick_fi',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('keywords', models.TextField()),
                ('search_id', models.IntegerField()),
                ('position', models.IntegerField()),
                ('ip', models.CharField(unique=True, max_length=16)),
                ('url', models.TextField(db_index=True)),
                ('click_time', models.DateTimeField(auto_now_add=True)),
                ('xpos', models.IntegerField(null=True, blank=True)),
                ('ypos', models.IntegerField(null=True, blank=True)),
            ],
            options={
                'abstract': False,
                'in_db': 'indexes',
            },
        ),
        migrations.CreateModel(
            name='ResultClick_fo',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('keywords', models.TextField()),
                ('search_id', models.IntegerField()),
                ('position', models.IntegerField()),
                ('ip', models.CharField(unique=True, max_length=16)),
                ('url', models.TextField(db_index=True)),
                ('click_time', models.DateTimeField(auto_now_add=True)),
                ('xpos', models.IntegerField(null=True, blank=True)),
                ('ypos', models.IntegerField(null=True, blank=True)),
            ],
            options={
                'abstract': False,
                'in_db': 'indexes',
            },
        ),
        migrations.CreateModel(
            name='ResultClick_fr',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('keywords', models.TextField()),
                ('search_id', models.IntegerField()),
                ('position', models.IntegerField()),
                ('ip', models.CharField(unique=True, max_length=16)),
                ('url', models.TextField(db_index=True)),
                ('click_time', models.DateTimeField(auto_now_add=True)),
                ('xpos', models.IntegerField(null=True, blank=True)),
                ('ypos', models.IntegerField(null=True, blank=True)),
            ],
            options={
                'abstract': False,
                'in_db': 'indexes',
            },
        ),
        migrations.CreateModel(
            name='ResultClick_fy',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('keywords', models.TextField()),
                ('search_id', models.IntegerField()),
                ('position', models.IntegerField()),
                ('ip', models.CharField(unique=True, max_length=16)),
                ('url', models.TextField(db_index=True)),
                ('click_time', models.DateTimeField(auto_now_add=True)),
                ('xpos', models.IntegerField(null=True, blank=True)),
                ('ypos', models.IntegerField(null=True, blank=True)),
            ],
            options={
                'abstract': False,
                'in_db': 'indexes',
            },
        ),
        migrations.CreateModel(
            name='ResultClick_gl',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('keywords', models.TextField()),
                ('search_id', models.IntegerField()),
                ('position', models.IntegerField()),
                ('ip', models.CharField(unique=True, max_length=16)),
                ('url', models.TextField(db_index=True)),
                ('click_time', models.DateTimeField(auto_now_add=True)),
                ('xpos', models.IntegerField(null=True, blank=True)),
                ('ypos', models.IntegerField(null=True, blank=True)),
            ],
            options={
                'abstract': False,
                'in_db': 'indexes',
            },
        ),
        migrations.CreateModel(
            name='ResultClick_ha',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('keywords', models.TextField()),
                ('search_id', models.IntegerField()),
                ('position', models.IntegerField()),
                ('ip', models.CharField(unique=True, max_length=16)),
                ('url', models.TextField(db_index=True)),
                ('click_time', models.DateTimeField(auto_now_add=True)),
                ('xpos', models.IntegerField(null=True, blank=True)),
                ('ypos', models.IntegerField(null=True, blank=True)),
            ],
            options={
                'abstract': False,
                'in_db': 'indexes',
            },
        ),
        migrations.CreateModel(
            name='ResultClick_hr',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('keywords', models.TextField()),
                ('search_id', models.IntegerField()),
                ('position', models.IntegerField()),
                ('ip', models.CharField(unique=True, max_length=16)),
                ('url', models.TextField(db_index=True)),
                ('click_time', models.DateTimeField(auto_now_add=True)),
                ('xpos', models.IntegerField(null=True, blank=True)),
                ('ypos', models.IntegerField(null=True, blank=True)),
            ],
            options={
                'abstract': False,
                'in_db': 'indexes',
            },
        ),
        migrations.CreateModel(
            name='ResultClick_hu',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('keywords', models.TextField()),
                ('search_id', models.IntegerField()),
                ('position', models.IntegerField()),
                ('ip', models.CharField(unique=True, max_length=16)),
                ('url', models.TextField(db_index=True)),
                ('click_time', models.DateTimeField(auto_now_add=True)),
                ('xpos', models.IntegerField(null=True, blank=True)),
                ('ypos', models.IntegerField(null=True, blank=True)),
            ],
            options={
                'abstract': False,
                'in_db': 'indexes',
            },
        ),
        migrations.CreateModel(
            name='ResultClick_ig',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('keywords', models.TextField()),
                ('search_id', models.IntegerField()),
                ('position', models.IntegerField()),
                ('ip', models.CharField(unique=True, max_length=16)),
                ('url', models.TextField(db_index=True)),
                ('click_time', models.DateTimeField(auto_now_add=True)),
                ('xpos', models.IntegerField(null=True, blank=True)),
                ('ypos', models.IntegerField(null=True, blank=True)),
            ],
            options={
                'abstract': False,
                'in_db': 'indexes',
            },
        ),
        migrations.CreateModel(
            name='ResultClick_is',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('keywords', models.TextField()),
                ('search_id', models.IntegerField()),
                ('position', models.IntegerField()),
                ('ip', models.CharField(unique=True, max_length=16)),
                ('url', models.TextField(db_index=True)),
                ('click_time', models.DateTimeField(auto_now_add=True)),
                ('xpos', models.IntegerField(null=True, blank=True)),
                ('ypos', models.IntegerField(null=True, blank=True)),
            ],
            options={
                'abstract': False,
                'in_db': 'indexes',
            },
        ),
        migrations.CreateModel(
            name='ResultClick_it',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('keywords', models.TextField()),
                ('search_id', models.IntegerField()),
                ('position', models.IntegerField()),
                ('ip', models.CharField(unique=True, max_length=16)),
                ('url', models.TextField(db_index=True)),
                ('click_time', models.DateTimeField(auto_now_add=True)),
                ('xpos', models.IntegerField(null=True, blank=True)),
                ('ypos', models.IntegerField(null=True, blank=True)),
            ],
            options={
                'abstract': False,
                'in_db': 'indexes',
            },
        ),
        migrations.CreateModel(
            name='ResultClick_kg',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('keywords', models.TextField()),
                ('search_id', models.IntegerField()),
                ('position', models.IntegerField()),
                ('ip', models.CharField(unique=True, max_length=16)),
                ('url', models.TextField(db_index=True)),
                ('click_time', models.DateTimeField(auto_now_add=True)),
                ('xpos', models.IntegerField(null=True, blank=True)),
                ('ypos', models.IntegerField(null=True, blank=True)),
            ],
            options={
                'abstract': False,
                'in_db': 'indexes',
            },
        ),
        migrations.CreateModel(
            name='ResultClick_ki',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('keywords', models.TextField()),
                ('search_id', models.IntegerField()),
                ('position', models.IntegerField()),
                ('ip', models.CharField(unique=True, max_length=16)),
                ('url', models.TextField(db_index=True)),
                ('click_time', models.DateTimeField(auto_now_add=True)),
                ('xpos', models.IntegerField(null=True, blank=True)),
                ('ypos', models.IntegerField(null=True, blank=True)),
            ],
            options={
                'abstract': False,
                'in_db': 'indexes',
            },
        ),
        migrations.CreateModel(
            name='ResultClick_la',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('keywords', models.TextField()),
                ('search_id', models.IntegerField()),
                ('position', models.IntegerField()),
                ('ip', models.CharField(unique=True, max_length=16)),
                ('url', models.TextField(db_index=True)),
                ('click_time', models.DateTimeField(auto_now_add=True)),
                ('xpos', models.IntegerField(null=True, blank=True)),
                ('ypos', models.IntegerField(null=True, blank=True)),
            ],
            options={
                'abstract': False,
                'in_db': 'indexes',
            },
        ),
        migrations.CreateModel(
            name='ResultClick_lg',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('keywords', models.TextField()),
                ('search_id', models.IntegerField()),
                ('position', models.IntegerField()),
                ('ip', models.CharField(unique=True, max_length=16)),
                ('url', models.TextField(db_index=True)),
                ('click_time', models.DateTimeField(auto_now_add=True)),
                ('xpos', models.IntegerField(null=True, blank=True)),
                ('ypos', models.IntegerField(null=True, blank=True)),
            ],
            options={
                'abstract': False,
                'in_db': 'indexes',
            },
        ),
        migrations.CreateModel(
            name='ResultClick_ln',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('keywords', models.TextField()),
                ('search_id', models.IntegerField()),
                ('position', models.IntegerField()),
                ('ip', models.CharField(unique=True, max_length=16)),
                ('url', models.TextField(db_index=True)),
                ('click_time', models.DateTimeField(auto_now_add=True)),
                ('xpos', models.IntegerField(null=True, blank=True)),
                ('ypos', models.IntegerField(null=True, blank=True)),
            ],
            options={
                'abstract': False,
                'in_db': 'indexes',
            },
        ),
        migrations.CreateModel(
            name='ResultClick_lt',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('keywords', models.TextField()),
                ('search_id', models.IntegerField()),
                ('position', models.IntegerField()),
                ('ip', models.CharField(unique=True, max_length=16)),
                ('url', models.TextField(db_index=True)),
                ('click_time', models.DateTimeField(auto_now_add=True)),
                ('xpos', models.IntegerField(null=True, blank=True)),
                ('ypos', models.IntegerField(null=True, blank=True)),
            ],
            options={
                'abstract': False,
                'in_db': 'indexes',
            },
        ),
        migrations.CreateModel(
            name='ResultClick_lv',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('keywords', models.TextField()),
                ('search_id', models.IntegerField()),
                ('position', models.IntegerField()),
                ('ip', models.CharField(unique=True, max_length=16)),
                ('url', models.TextField(db_index=True)),
                ('click_time', models.DateTimeField(auto_now_add=True)),
                ('xpos', models.IntegerField(null=True, blank=True)),
                ('ypos', models.IntegerField(null=True, blank=True)),
            ],
            options={
                'abstract': False,
                'in_db': 'indexes',
            },
        ),
        migrations.CreateModel(
            name='ResultClick_nap',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('keywords', models.TextField()),
                ('search_id', models.IntegerField()),
                ('position', models.IntegerField()),
                ('ip', models.CharField(unique=True, max_length=16)),
                ('url', models.TextField(db_index=True)),
                ('click_time', models.DateTimeField(auto_now_add=True)),
                ('xpos', models.IntegerField(null=True, blank=True)),
                ('ypos', models.IntegerField(null=True, blank=True)),
            ],
            options={
                'abstract': False,
                'in_db': 'indexes',
            },
        ),
        migrations.CreateModel(
            name='ResultClick_nl',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('keywords', models.TextField()),
                ('search_id', models.IntegerField()),
                ('position', models.IntegerField()),
                ('ip', models.CharField(unique=True, max_length=16)),
                ('url', models.TextField(db_index=True)),
                ('click_time', models.DateTimeField(auto_now_add=True)),
                ('xpos', models.IntegerField(null=True, blank=True)),
                ('ypos', models.IntegerField(null=True, blank=True)),
            ],
            options={
                'abstract': False,
                'in_db': 'indexes',
            },
        ),
        migrations.CreateModel(
            name='ResultClick_no',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('keywords', models.TextField()),
                ('search_id', models.IntegerField()),
                ('position', models.IntegerField()),
                ('ip', models.CharField(unique=True, max_length=16)),
                ('url', models.TextField(db_index=True)),
                ('click_time', models.DateTimeField(auto_now_add=True)),
                ('xpos', models.IntegerField(null=True, blank=True)),
                ('ypos', models.IntegerField(null=True, blank=True)),
            ],
            options={
                'abstract': False,
                'in_db': 'indexes',
            },
        ),
        migrations.CreateModel(
            name='ResultClick_nso',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('keywords', models.TextField()),
                ('search_id', models.IntegerField()),
                ('position', models.IntegerField()),
                ('ip', models.CharField(unique=True, max_length=16)),
                ('url', models.TextField(db_index=True)),
                ('click_time', models.DateTimeField(auto_now_add=True)),
                ('xpos', models.IntegerField(null=True, blank=True)),
                ('ypos', models.IntegerField(null=True, blank=True)),
            ],
            options={
                'abstract': False,
                'in_db': 'indexes',
            },
        ),
        migrations.CreateModel(
            name='ResultClick_ny',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('keywords', models.TextField()),
                ('search_id', models.IntegerField()),
                ('position', models.IntegerField()),
                ('ip', models.CharField(unique=True, max_length=16)),
                ('url', models.TextField(db_index=True)),
                ('click_time', models.DateTimeField(auto_now_add=True)),
                ('xpos', models.IntegerField(null=True, blank=True)),
                ('ypos', models.IntegerField(null=True, blank=True)),
            ],
            options={
                'abstract': False,
                'in_db': 'indexes',
            },
        ),
        migrations.CreateModel(
            name='ResultClick_oc',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('keywords', models.TextField()),
                ('search_id', models.IntegerField()),
                ('position', models.IntegerField()),
                ('ip', models.CharField(unique=True, max_length=16)),
                ('url', models.TextField(db_index=True)),
                ('click_time', models.DateTimeField(auto_now_add=True)),
                ('xpos', models.IntegerField(null=True, blank=True)),
                ('ypos', models.IntegerField(null=True, blank=True)),
            ],
            options={
                'abstract': False,
                'in_db': 'indexes',
            },
        ),
        migrations.CreateModel(
            name='ResultClick_om',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('keywords', models.TextField()),
                ('search_id', models.IntegerField()),
                ('position', models.IntegerField()),
                ('ip', models.CharField(unique=True, max_length=16)),
                ('url', models.TextField(db_index=True)),
                ('click_time', models.DateTimeField(auto_now_add=True)),
                ('xpos', models.IntegerField(null=True, blank=True)),
                ('ypos', models.IntegerField(null=True, blank=True)),
            ],
            options={
                'abstract': False,
                'in_db': 'indexes',
            },
        ),
        migrations.CreateModel(
            name='ResultClick_pl',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('keywords', models.TextField()),
                ('search_id', models.IntegerField()),
                ('position', models.IntegerField()),
                ('ip', models.CharField(unique=True, max_length=16)),
                ('url', models.TextField(db_index=True)),
                ('click_time', models.DateTimeField(auto_now_add=True)),
                ('xpos', models.IntegerField(null=True, blank=True)),
                ('ypos', models.IntegerField(null=True, blank=True)),
            ],
            options={
                'abstract': False,
                'in_db': 'indexes',
            },
        ),
        migrations.CreateModel(
            name='ResultClick_pms',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('keywords', models.TextField()),
                ('search_id', models.IntegerField()),
                ('position', models.IntegerField()),
                ('ip', models.CharField(unique=True, max_length=16)),
                ('url', models.TextField(db_index=True)),
                ('click_time', models.DateTimeField(auto_now_add=True)),
                ('xpos', models.IntegerField(null=True, blank=True)),
                ('ypos', models.IntegerField(null=True, blank=True)),
            ],
            options={
                'abstract': False,
                'in_db': 'indexes',
            },
        ),
        migrations.CreateModel(
            name='ResultClick_pt',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('keywords', models.TextField()),
                ('search_id', models.IntegerField()),
                ('position', models.IntegerField()),
                ('ip', models.CharField(unique=True, max_length=16)),
                ('url', models.TextField(db_index=True)),
                ('click_time', models.DateTimeField(auto_now_add=True)),
                ('xpos', models.IntegerField(null=True, blank=True)),
                ('ypos', models.IntegerField(null=True, blank=True)),
            ],
            options={
                'abstract': False,
                'in_db': 'indexes',
            },
        ),
        migrations.CreateModel(
            name='ResultClick_rn',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('keywords', models.TextField()),
                ('search_id', models.IntegerField()),
                ('position', models.IntegerField()),
                ('ip', models.CharField(unique=True, max_length=16)),
                ('url', models.TextField(db_index=True)),
                ('click_time', models.DateTimeField(auto_now_add=True)),
                ('xpos', models.IntegerField(null=True, blank=True)),
                ('ypos', models.IntegerField(null=True, blank=True)),
            ],
            options={
                'abstract': False,
                'in_db': 'indexes',
            },
        ),
        migrations.CreateModel(
            name='ResultClick_ro',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('keywords', models.TextField()),
                ('search_id', models.IntegerField()),
                ('position', models.IntegerField()),
                ('ip', models.CharField(unique=True, max_length=16)),
                ('url', models.TextField(db_index=True)),
                ('click_time', models.DateTimeField(auto_now_add=True)),
                ('xpos', models.IntegerField(null=True, blank=True)),
                ('ypos', models.IntegerField(null=True, blank=True)),
            ],
            options={
                'abstract': False,
                'in_db': 'indexes',
            },
        ),
        migrations.CreateModel(
            name='ResultClick_rw',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('keywords', models.TextField()),
                ('search_id', models.IntegerField()),
                ('position', models.IntegerField()),
                ('ip', models.CharField(unique=True, max_length=16)),
                ('url', models.TextField(db_index=True)),
                ('click_time', models.DateTimeField(auto_now_add=True)),
                ('xpos', models.IntegerField(null=True, blank=True)),
                ('ypos', models.IntegerField(null=True, blank=True)),
            ],
            options={
                'abstract': False,
                'in_db': 'indexes',
            },
        ),
        migrations.CreateModel(
            name='ResultClick_sc',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('keywords', models.TextField()),
                ('search_id', models.IntegerField()),
                ('position', models.IntegerField()),
                ('ip', models.CharField(unique=True, max_length=16)),
                ('url', models.TextField(db_index=True)),
                ('click_time', models.DateTimeField(auto_now_add=True)),
                ('xpos', models.IntegerField(null=True, blank=True)),
                ('ypos', models.IntegerField(null=True, blank=True)),
            ],
            options={
                'abstract': False,
                'in_db': 'indexes',
            },
        ),
        migrations.CreateModel(
            name='ResultClick_scn',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('keywords', models.TextField()),
                ('search_id', models.IntegerField()),
                ('position', models.IntegerField()),
                ('ip', models.CharField(unique=True, max_length=16)),
                ('url', models.TextField(db_index=True)),
                ('click_time', models.DateTimeField(auto_now_add=True)),
                ('xpos', models.IntegerField(null=True, blank=True)),
                ('ypos', models.IntegerField(null=True, blank=True)),
            ],
            options={
                'abstract': False,
                'in_db': 'indexes',
            },
        ),
        migrations.CreateModel(
            name='ResultClick_sk',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('keywords', models.TextField()),
                ('search_id', models.IntegerField()),
                ('position', models.IntegerField()),
                ('ip', models.CharField(unique=True, max_length=16)),
                ('url', models.TextField(db_index=True)),
                ('click_time', models.DateTimeField(auto_now_add=True)),
                ('xpos', models.IntegerField(null=True, blank=True)),
                ('ypos', models.IntegerField(null=True, blank=True)),
            ],
            options={
                'abstract': False,
                'in_db': 'indexes',
            },
        ),
        migrations.CreateModel(
            name='ResultClick_sl',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('keywords', models.TextField()),
                ('search_id', models.IntegerField()),
                ('position', models.IntegerField()),
                ('ip', models.CharField(unique=True, max_length=16)),
                ('url', models.TextField(db_index=True)),
                ('click_time', models.DateTimeField(auto_now_add=True)),
                ('xpos', models.IntegerField(null=True, blank=True)),
                ('ypos', models.IntegerField(null=True, blank=True)),
            ],
            options={
                'abstract': False,
                'in_db': 'indexes',
            },
        ),
        migrations.CreateModel(
            name='ResultClick_sn',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('keywords', models.TextField()),
                ('search_id', models.IntegerField()),
                ('position', models.IntegerField()),
                ('ip', models.CharField(unique=True, max_length=16)),
                ('url', models.TextField(db_index=True)),
                ('click_time', models.DateTimeField(auto_now_add=True)),
                ('xpos', models.IntegerField(null=True, blank=True)),
                ('ypos', models.IntegerField(null=True, blank=True)),
            ],
            options={
                'abstract': False,
                'in_db': 'indexes',
            },
        ),
        migrations.CreateModel(
            name='ResultClick_so',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('keywords', models.TextField()),
                ('search_id', models.IntegerField()),
                ('position', models.IntegerField()),
                ('ip', models.CharField(unique=True, max_length=16)),
                ('url', models.TextField(db_index=True)),
                ('click_time', models.DateTimeField(auto_now_add=True)),
                ('xpos', models.IntegerField(null=True, blank=True)),
                ('ypos', models.IntegerField(null=True, blank=True)),
            ],
            options={
                'abstract': False,
                'in_db': 'indexes',
            },
        ),
        migrations.CreateModel(
            name='ResultClick_ss',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('keywords', models.TextField()),
                ('search_id', models.IntegerField()),
                ('position', models.IntegerField()),
                ('ip', models.CharField(unique=True, max_length=16)),
                ('url', models.TextField(db_index=True)),
                ('click_time', models.DateTimeField(auto_now_add=True)),
                ('xpos', models.IntegerField(null=True, blank=True)),
                ('ypos', models.IntegerField(null=True, blank=True)),
            ],
            options={
                'abstract': False,
                'in_db': 'indexes',
            },
        ),
        migrations.CreateModel(
            name='ResultClick_st',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('keywords', models.TextField()),
                ('search_id', models.IntegerField()),
                ('position', models.IntegerField()),
                ('ip', models.CharField(unique=True, max_length=16)),
                ('url', models.TextField(db_index=True)),
                ('click_time', models.DateTimeField(auto_now_add=True)),
                ('xpos', models.IntegerField(null=True, blank=True)),
                ('ypos', models.IntegerField(null=True, blank=True)),
            ],
            options={
                'abstract': False,
                'in_db': 'indexes',
            },
        ),
        migrations.CreateModel(
            name='ResultClick_sv',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('keywords', models.TextField()),
                ('search_id', models.IntegerField()),
                ('position', models.IntegerField()),
                ('ip', models.CharField(unique=True, max_length=16)),
                ('url', models.TextField(db_index=True)),
                ('click_time', models.DateTimeField(auto_now_add=True)),
                ('xpos', models.IntegerField(null=True, blank=True)),
                ('ypos', models.IntegerField(null=True, blank=True)),
            ],
            options={
                'abstract': False,
                'in_db': 'indexes',
            },
        ),
        migrations.CreateModel(
            name='ResultClick_sw',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('keywords', models.TextField()),
                ('search_id', models.IntegerField()),
                ('position', models.IntegerField()),
                ('ip', models.CharField(unique=True, max_length=16)),
                ('url', models.TextField(db_index=True)),
                ('click_time', models.DateTimeField(auto_now_add=True)),
                ('xpos', models.IntegerField(null=True, blank=True)),
                ('ypos', models.IntegerField(null=True, blank=True)),
            ],
            options={
                'abstract': False,
                'in_db': 'indexes',
            },
        ),
        migrations.CreateModel(
            name='ResultClick_tn',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('keywords', models.TextField()),
                ('search_id', models.IntegerField()),
                ('position', models.IntegerField()),
                ('ip', models.CharField(unique=True, max_length=16)),
                ('url', models.TextField(db_index=True)),
                ('click_time', models.DateTimeField(auto_now_add=True)),
                ('xpos', models.IntegerField(null=True, blank=True)),
                ('ypos', models.IntegerField(null=True, blank=True)),
            ],
            options={
                'abstract': False,
                'in_db': 'indexes',
            },
        ),
        migrations.CreateModel(
            name='ResultClick_tr',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('keywords', models.TextField()),
                ('search_id', models.IntegerField()),
                ('position', models.IntegerField()),
                ('ip', models.CharField(unique=True, max_length=16)),
                ('url', models.TextField(db_index=True)),
                ('click_time', models.DateTimeField(auto_now_add=True)),
                ('xpos', models.IntegerField(null=True, blank=True)),
                ('ypos', models.IntegerField(null=True, blank=True)),
            ],
            options={
                'abstract': False,
                'in_db': 'indexes',
            },
        ),
        migrations.CreateModel(
            name='ResultClick_ts',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('keywords', models.TextField()),
                ('search_id', models.IntegerField()),
                ('position', models.IntegerField()),
                ('ip', models.CharField(unique=True, max_length=16)),
                ('url', models.TextField(db_index=True)),
                ('click_time', models.DateTimeField(auto_now_add=True)),
                ('xpos', models.IntegerField(null=True, blank=True)),
                ('ypos', models.IntegerField(null=True, blank=True)),
            ],
            options={
                'abstract': False,
                'in_db': 'indexes',
            },
        ),
        migrations.CreateModel(
            name='ResultClick_ve',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('keywords', models.TextField()),
                ('search_id', models.IntegerField()),
                ('position', models.IntegerField()),
                ('ip', models.CharField(unique=True, max_length=16)),
                ('url', models.TextField(db_index=True)),
                ('click_time', models.DateTimeField(auto_now_add=True)),
                ('xpos', models.IntegerField(null=True, blank=True)),
                ('ypos', models.IntegerField(null=True, blank=True)),
            ],
            options={
                'abstract': False,
                'in_db': 'indexes',
            },
        ),
        migrations.CreateModel(
            name='ResultClick_vec',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('keywords', models.TextField()),
                ('search_id', models.IntegerField()),
                ('position', models.IntegerField()),
                ('ip', models.CharField(unique=True, max_length=16)),
                ('url', models.TextField(db_index=True)),
                ('click_time', models.DateTimeField(auto_now_add=True)),
                ('xpos', models.IntegerField(null=True, blank=True)),
                ('ypos', models.IntegerField(null=True, blank=True)),
            ],
            options={
                'abstract': False,
                'in_db': 'indexes',
            },
        ),
        migrations.CreateModel(
            name='ResultClick_wo',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('keywords', models.TextField()),
                ('search_id', models.IntegerField()),
                ('position', models.IntegerField()),
                ('ip', models.CharField(unique=True, max_length=16)),
                ('url', models.TextField(db_index=True)),
                ('click_time', models.DateTimeField(auto_now_add=True)),
                ('xpos', models.IntegerField(null=True, blank=True)),
                ('ypos', models.IntegerField(null=True, blank=True)),
            ],
            options={
                'abstract': False,
                'in_db': 'indexes',
            },
        ),
        migrations.CreateModel(
            name='ResultClick_xh',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('keywords', models.TextField()),
                ('search_id', models.IntegerField()),
                ('position', models.IntegerField()),
                ('ip', models.CharField(unique=True, max_length=16)),
                ('url', models.TextField(db_index=True)),
                ('click_time', models.DateTimeField(auto_now_add=True)),
                ('xpos', models.IntegerField(null=True, blank=True)),
                ('ypos', models.IntegerField(null=True, blank=True)),
            ],
            options={
                'abstract': False,
                'in_db': 'indexes',
            },
        ),
        migrations.CreateModel(
            name='ResultClick_yo',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('keywords', models.TextField()),
                ('search_id', models.IntegerField()),
                ('position', models.IntegerField()),
                ('ip', models.CharField(unique=True, max_length=16)),
                ('url', models.TextField(db_index=True)),
                ('click_time', models.DateTimeField(auto_now_add=True)),
                ('xpos', models.IntegerField(null=True, blank=True)),
                ('ypos', models.IntegerField(null=True, blank=True)),
            ],
            options={
                'abstract': False,
                'in_db': 'indexes',
            },
        ),
        migrations.CreateModel(
            name='ResultClick_zu',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('keywords', models.TextField()),
                ('search_id', models.IntegerField()),
                ('position', models.IntegerField()),
                ('ip', models.CharField(unique=True, max_length=16)),
                ('url', models.TextField(db_index=True)),
                ('click_time', models.DateTimeField(auto_now_add=True)),
                ('xpos', models.IntegerField(null=True, blank=True)),
                ('ypos', models.IntegerField(null=True, blank=True)),
            ],
            options={
                'abstract': False,
                'in_db': 'indexes',
            },
        ),
    ]
