# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dir', '0029_merge'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AutoComplete_af',
        ),
        migrations.DeleteModel(
            name='AutoComplete_ak',
        ),
        migrations.DeleteModel(
            name='AutoComplete_bm',
        ),
        migrations.DeleteModel(
            name='AutoComplete_br',
        ),
        migrations.DeleteModel(
            name='AutoComplete_cy',
        ),
        migrations.DeleteModel(
            name='AutoComplete_ee',
        ),
        migrations.DeleteModel(
            name='AutoComplete_eo',
        ),
        migrations.DeleteModel(
            name='AutoComplete_et',
        ),
        migrations.DeleteModel(
            name='AutoComplete_eu',
        ),
        migrations.DeleteModel(
            name='AutoComplete_ff',
        ),
        migrations.DeleteModel(
            name='AutoComplete_fo',
        ),
        migrations.DeleteModel(
            name='AutoComplete_fy',
        ),
        migrations.DeleteModel(
            name='AutoComplete_gl',
        ),
        migrations.DeleteModel(
            name='AutoComplete_ha',
        ),
        migrations.DeleteModel(
            name='AutoComplete_ig',
        ),
        migrations.DeleteModel(
            name='AutoComplete_is',
        ),
        migrations.DeleteModel(
            name='AutoComplete_kg',
        ),
        migrations.DeleteModel(
            name='AutoComplete_ki',
        ),
        migrations.DeleteModel(
            name='AutoComplete_la',
        ),
        migrations.DeleteModel(
            name='AutoComplete_lg',
        ),
        migrations.DeleteModel(
            name='AutoComplete_ln',
        ),
        migrations.DeleteModel(
            name='AutoComplete_lt',
        ),
        migrations.DeleteModel(
            name='AutoComplete_lv',
        ),
        migrations.DeleteModel(
            name='AutoComplete_nap',
        ),
        migrations.DeleteModel(
            name='AutoComplete_nso',
        ),
        migrations.DeleteModel(
            name='AutoComplete_ny',
        ),
        migrations.DeleteModel(
            name='AutoComplete_oc',
        ),
        migrations.DeleteModel(
            name='AutoComplete_om',
        ),
        migrations.DeleteModel(
            name='AutoComplete_pms',
        ),
        migrations.DeleteModel(
            name='AutoComplete_rn',
        ),
        migrations.DeleteModel(
            name='AutoComplete_rw',
        ),
        migrations.DeleteModel(
            name='AutoComplete_sc',
        ),
        migrations.DeleteModel(
            name='AutoComplete_scn',
        ),
        migrations.DeleteModel(
            name='AutoComplete_ss',
        ),
        migrations.DeleteModel(
            name='AutoComplete_st',
        ),
        migrations.DeleteModel(
            name='AutoComplete_sw',
        ),
        migrations.DeleteModel(
            name='AutoComplete_tn',
        ),
        migrations.DeleteModel(
            name='AutoComplete_ts',
        ),
        migrations.DeleteModel(
            name='AutoComplete_ve',
        ),
        migrations.DeleteModel(
            name='AutoComplete_vec',
        ),
        migrations.DeleteModel(
            name='AutoComplete_wo',
        ),
        migrations.DeleteModel(
            name='AutoComplete_xh',
        ),
        migrations.DeleteModel(
            name='AutoComplete_yo',
        ),
        migrations.DeleteModel(
            name='AutoComplete_zu',
        ),
        migrations.DeleteModel(
            name='IndexTerm_af',
        ),
        migrations.DeleteModel(
            name='IndexTerm_ak',
        ),
        migrations.DeleteModel(
            name='IndexTerm_bm',
        ),
        migrations.DeleteModel(
            name='IndexTerm_br',
        ),
        migrations.DeleteModel(
            name='IndexTerm_cy',
        ),
        migrations.DeleteModel(
            name='IndexTerm_ee',
        ),
        migrations.DeleteModel(
            name='IndexTerm_eo',
        ),
        migrations.DeleteModel(
            name='IndexTerm_et',
        ),
        migrations.DeleteModel(
            name='IndexTerm_eu',
        ),
        migrations.DeleteModel(
            name='IndexTerm_ff',
        ),
        migrations.DeleteModel(
            name='IndexTerm_fo',
        ),
        migrations.DeleteModel(
            name='IndexTerm_fy',
        ),
        migrations.DeleteModel(
            name='IndexTerm_gl',
        ),
        migrations.DeleteModel(
            name='IndexTerm_ha',
        ),
        migrations.DeleteModel(
            name='IndexTerm_hr',
        ),
        migrations.DeleteModel(
            name='IndexTerm_ig',
        ),
        migrations.DeleteModel(
            name='IndexTerm_is',
        ),
        migrations.DeleteModel(
            name='IndexTerm_kg',
        ),
        migrations.DeleteModel(
            name='IndexTerm_ki',
        ),
        migrations.DeleteModel(
            name='IndexTerm_la',
        ),
        migrations.DeleteModel(
            name='IndexTerm_lg',
        ),
        migrations.DeleteModel(
            name='IndexTerm_ln',
        ),
        migrations.DeleteModel(
            name='IndexTerm_lt',
        ),
        migrations.DeleteModel(
            name='IndexTerm_lv',
        ),
        migrations.DeleteModel(
            name='IndexTerm_nap',
        ),
        migrations.DeleteModel(
            name='IndexTerm_nso',
        ),
        migrations.DeleteModel(
            name='IndexTerm_ny',
        ),
        migrations.DeleteModel(
            name='IndexTerm_oc',
        ),
        migrations.DeleteModel(
            name='IndexTerm_om',
        ),
        migrations.DeleteModel(
            name='IndexTerm_pms',
        ),
        migrations.DeleteModel(
            name='IndexTerm_rn',
        ),
        migrations.DeleteModel(
            name='IndexTerm_rw',
        ),
        migrations.DeleteModel(
            name='IndexTerm_sc',
        ),
        migrations.DeleteModel(
            name='IndexTerm_scn',
        ),
        migrations.DeleteModel(
            name='IndexTerm_ss',
        ),
        migrations.DeleteModel(
            name='IndexTerm_st',
        ),
        migrations.DeleteModel(
            name='IndexTerm_sw',
        ),
        migrations.DeleteModel(
            name='IndexTerm_tn',
        ),
        migrations.DeleteModel(
            name='IndexTerm_ts',
        ),
        migrations.DeleteModel(
            name='IndexTerm_ve',
        ),
        migrations.DeleteModel(
            name='IndexTerm_vec',
        ),
        migrations.DeleteModel(
            name='IndexTerm_wo',
        ),
        migrations.DeleteModel(
            name='IndexTerm_xh',
        ),
        migrations.DeleteModel(
            name='IndexTerm_yo',
        ),
        migrations.DeleteModel(
            name='IndexTerm_zu',
        ),
        migrations.DeleteModel(
            name='KeywordRanking_af',
        ),
        migrations.DeleteModel(
            name='KeywordRanking_ak',
        ),
        migrations.DeleteModel(
            name='KeywordRanking_bm',
        ),
        migrations.DeleteModel(
            name='KeywordRanking_br',
        ),
        migrations.DeleteModel(
            name='KeywordRanking_ca',
        ),
        migrations.DeleteModel(
            name='KeywordRanking_cy',
        ),
        migrations.DeleteModel(
            name='KeywordRanking_ee',
        ),
        migrations.DeleteModel(
            name='KeywordRanking_eo',
        ),
        migrations.DeleteModel(
            name='KeywordRanking_et',
        ),
        migrations.DeleteModel(
            name='KeywordRanking_eu',
        ),
        migrations.DeleteModel(
            name='KeywordRanking_ff',
        ),
        migrations.DeleteModel(
            name='KeywordRanking_fo',
        ),
        migrations.DeleteModel(
            name='KeywordRanking_fy',
        ),
        migrations.DeleteModel(
            name='KeywordRanking_gl',
        ),
        migrations.DeleteModel(
            name='KeywordRanking_ha',
        ),
        migrations.DeleteModel(
            name='KeywordRanking_ig',
        ),
        migrations.DeleteModel(
            name='KeywordRanking_is',
        ),
        migrations.DeleteModel(
            name='KeywordRanking_kg',
        ),
        migrations.DeleteModel(
            name='KeywordRanking_ki',
        ),
        migrations.DeleteModel(
            name='KeywordRanking_la',
        ),
        migrations.DeleteModel(
            name='KeywordRanking_lg',
        ),
        migrations.DeleteModel(
            name='KeywordRanking_ln',
        ),
        migrations.DeleteModel(
            name='KeywordRanking_lt',
        ),
        migrations.DeleteModel(
            name='KeywordRanking_lv',
        ),
        migrations.DeleteModel(
            name='KeywordRanking_nap',
        ),
        migrations.DeleteModel(
            name='KeywordRanking_nso',
        ),
        migrations.DeleteModel(
            name='KeywordRanking_ny',
        ),
        migrations.DeleteModel(
            name='KeywordRanking_oc',
        ),
        migrations.DeleteModel(
            name='KeywordRanking_om',
        ),
        migrations.DeleteModel(
            name='KeywordRanking_pms',
        ),
        migrations.DeleteModel(
            name='KeywordRanking_rn',
        ),
        migrations.DeleteModel(
            name='KeywordRanking_rw',
        ),
        migrations.DeleteModel(
            name='KeywordRanking_sc',
        ),
        migrations.DeleteModel(
            name='KeywordRanking_scn',
        ),
        migrations.DeleteModel(
            name='KeywordRanking_ss',
        ),
        migrations.DeleteModel(
            name='KeywordRanking_st',
        ),
        migrations.DeleteModel(
            name='KeywordRanking_sw',
        ),
        migrations.DeleteModel(
            name='KeywordRanking_tn',
        ),
        migrations.DeleteModel(
            name='KeywordRanking_ts',
        ),
        migrations.DeleteModel(
            name='KeywordRanking_ve',
        ),
        migrations.DeleteModel(
            name='KeywordRanking_vec',
        ),
        migrations.DeleteModel(
            name='KeywordRanking_wo',
        ),
        migrations.DeleteModel(
            name='KeywordRanking_xh',
        ),
        migrations.DeleteModel(
            name='KeywordRanking_yo',
        ),
        migrations.DeleteModel(
            name='KeywordRanking_zu',
        ),
        migrations.DeleteModel(
            name='PendingIndex_af',
        ),
        migrations.DeleteModel(
            name='PendingIndex_ak',
        ),
        migrations.DeleteModel(
            name='PendingIndex_bm',
        ),
        migrations.DeleteModel(
            name='PendingIndex_br',
        ),
        migrations.DeleteModel(
            name='PendingIndex_cy',
        ),
        migrations.DeleteModel(
            name='PendingIndex_ee',
        ),
        migrations.DeleteModel(
            name='PendingIndex_eo',
        ),
        migrations.DeleteModel(
            name='PendingIndex_et',
        ),
        migrations.DeleteModel(
            name='PendingIndex_eu',
        ),
        migrations.DeleteModel(
            name='PendingIndex_ff',
        ),
        migrations.DeleteModel(
            name='PendingIndex_fo',
        ),
        migrations.DeleteModel(
            name='PendingIndex_fy',
        ),
        migrations.DeleteModel(
            name='PendingIndex_gl',
        ),
        migrations.DeleteModel(
            name='PendingIndex_ha',
        ),
        migrations.DeleteModel(
            name='PendingIndex_hr',
        ),
        migrations.DeleteModel(
            name='PendingIndex_ig',
        ),
        migrations.DeleteModel(
            name='PendingIndex_is',
        ),
        migrations.DeleteModel(
            name='PendingIndex_kg',
        ),
        migrations.DeleteModel(
            name='PendingIndex_ki',
        ),
        migrations.DeleteModel(
            name='PendingIndex_la',
        ),
        migrations.DeleteModel(
            name='PendingIndex_lg',
        ),
        migrations.DeleteModel(
            name='PendingIndex_ln',
        ),
        migrations.DeleteModel(
            name='PendingIndex_lt',
        ),
        migrations.DeleteModel(
            name='PendingIndex_lv',
        ),
        migrations.DeleteModel(
            name='PendingIndex_nap',
        ),
        migrations.DeleteModel(
            name='PendingIndex_nso',
        ),
        migrations.DeleteModel(
            name='PendingIndex_ny',
        ),
        migrations.DeleteModel(
            name='PendingIndex_oc',
        ),
        migrations.DeleteModel(
            name='PendingIndex_om',
        ),
        migrations.DeleteModel(
            name='PendingIndex_pms',
        ),
        migrations.DeleteModel(
            name='PendingIndex_rn',
        ),
        migrations.DeleteModel(
            name='PendingIndex_rw',
        ),
        migrations.DeleteModel(
            name='PendingIndex_sc',
        ),
        migrations.DeleteModel(
            name='PendingIndex_scn',
        ),
        migrations.DeleteModel(
            name='PendingIndex_ss',
        ),
        migrations.DeleteModel(
            name='PendingIndex_st',
        ),
        migrations.DeleteModel(
            name='PendingIndex_sw',
        ),
        migrations.DeleteModel(
            name='PendingIndex_tn',
        ),
        migrations.DeleteModel(
            name='PendingIndex_ts',
        ),
        migrations.DeleteModel(
            name='PendingIndex_ve',
        ),
        migrations.DeleteModel(
            name='PendingIndex_vec',
        ),
        migrations.DeleteModel(
            name='PendingIndex_wo',
        ),
        migrations.DeleteModel(
            name='PendingIndex_xh',
        ),
        migrations.DeleteModel(
            name='PendingIndex_yo',
        ),
        migrations.DeleteModel(
            name='PendingIndex_zu',
        ),
        migrations.DeleteModel(
            name='ResultClick_af',
        ),
        migrations.DeleteModel(
            name='ResultClick_ak',
        ),
        migrations.DeleteModel(
            name='ResultClick_bm',
        ),
        migrations.DeleteModel(
            name='ResultClick_br',
        ),
        migrations.DeleteModel(
            name='ResultClick_cy',
        ),
        migrations.DeleteModel(
            name='ResultClick_eo',
        ),
        migrations.DeleteModel(
            name='ResultClick_et',
        ),
        migrations.DeleteModel(
            name='ResultClick_eu',
        ),
        migrations.DeleteModel(
            name='ResultClick_ff',
        ),
        migrations.DeleteModel(
            name='ResultClick_fo',
        ),
        migrations.DeleteModel(
            name='ResultClick_fy',
        ),
        migrations.DeleteModel(
            name='ResultClick_gl',
        ),
        migrations.DeleteModel(
            name='ResultClick_ig',
        ),
        migrations.DeleteModel(
            name='ResultClick_kg',
        ),
        migrations.DeleteModel(
            name='ResultClick_ki',
        ),
        migrations.DeleteModel(
            name='ResultClick_la',
        ),
        migrations.DeleteModel(
            name='ResultClick_lg',
        ),
        migrations.DeleteModel(
            name='ResultClick_ln',
        ),
        migrations.DeleteModel(
            name='ResultClick_nap',
        ),
        migrations.DeleteModel(
            name='ResultClick_nso',
        ),
        migrations.DeleteModel(
            name='ResultClick_ny',
        ),
        migrations.DeleteModel(
            name='ResultClick_oc',
        ),
        migrations.DeleteModel(
            name='ResultClick_om',
        ),
        migrations.DeleteModel(
            name='ResultClick_pms',
        ),
        migrations.DeleteModel(
            name='ResultClick_rn',
        ),
        migrations.DeleteModel(
            name='ResultClick_sc',
        ),
        migrations.DeleteModel(
            name='ResultClick_scn',
        ),
        migrations.DeleteModel(
            name='ResultClick_ss',
        ),
        migrations.DeleteModel(
            name='ResultClick_st',
        ),
        migrations.DeleteModel(
            name='ResultClick_tn',
        ),
        migrations.DeleteModel(
            name='ResultClick_ts',
        ),
        migrations.DeleteModel(
            name='ResultClick_ve',
        ),
        migrations.DeleteModel(
            name='ResultClick_vec',
        ),
        migrations.DeleteModel(
            name='ResultClick_xh',
        ),
        migrations.DeleteModel(
            name='ResultClick_zu',
        ),
        migrations.DeleteModel(
            name='SearchLog_af',
        ),
        migrations.DeleteModel(
            name='SearchLog_ak',
        ),
        migrations.DeleteModel(
            name='SearchLog_bm',
        ),
        migrations.DeleteModel(
            name='SearchLog_br',
        ),
        migrations.DeleteModel(
            name='SearchLog_cy',
        ),
        migrations.DeleteModel(
            name='SearchLog_eo',
        ),
        migrations.DeleteModel(
            name='SearchLog_et',
        ),
        migrations.DeleteModel(
            name='SearchLog_eu',
        ),
        migrations.DeleteModel(
            name='SearchLog_ff',
        ),
        migrations.DeleteModel(
            name='SearchLog_fo',
        ),
        migrations.DeleteModel(
            name='SearchLog_fy',
        ),
        migrations.DeleteModel(
            name='SearchLog_gl',
        ),
        migrations.DeleteModel(
            name='SearchLog_ig',
        ),
        migrations.DeleteModel(
            name='SearchLog_kg',
        ),
        migrations.DeleteModel(
            name='SearchLog_ki',
        ),
        migrations.DeleteModel(
            name='SearchLog_la',
        ),
        migrations.DeleteModel(
            name='SearchLog_lg',
        ),
        migrations.DeleteModel(
            name='SearchLog_ln',
        ),
        migrations.DeleteModel(
            name='SearchLog_nap',
        ),
        migrations.DeleteModel(
            name='SearchLog_nso',
        ),
        migrations.DeleteModel(
            name='SearchLog_ny',
        ),
        migrations.DeleteModel(
            name='SearchLog_oc',
        ),
        migrations.DeleteModel(
            name='SearchLog_om',
        ),
        migrations.DeleteModel(
            name='SearchLog_pms',
        ),
        migrations.DeleteModel(
            name='SearchLog_rn',
        ),
        migrations.DeleteModel(
            name='SearchLog_sc',
        ),
        migrations.DeleteModel(
            name='SearchLog_scn',
        ),
        migrations.DeleteModel(
            name='SearchLog_ss',
        ),
        migrations.DeleteModel(
            name='SearchLog_st',
        ),
        migrations.DeleteModel(
            name='SearchLog_tn',
        ),
        migrations.DeleteModel(
            name='SearchLog_ts',
        ),
        migrations.DeleteModel(
            name='SearchLog_ve',
        ),
        migrations.DeleteModel(
            name='SearchLog_vec',
        ),
        migrations.DeleteModel(
            name='SearchLog_xh',
        ),
        migrations.DeleteModel(
            name='SearchLog_zu',
        ),
        migrations.DeleteModel(
            name='SiteInfo_af',
        ),
        migrations.DeleteModel(
            name='SiteInfo_ak',
        ),
        migrations.DeleteModel(
            name='SiteInfo_bm',
        ),
        migrations.DeleteModel(
            name='SiteInfo_br',
        ),
        migrations.DeleteModel(
            name='SiteInfo_cy',
        ),
        migrations.DeleteModel(
            name='SiteInfo_ee',
        ),
        migrations.DeleteModel(
            name='SiteInfo_eo',
        ),
        migrations.DeleteModel(
            name='SiteInfo_et',
        ),
        migrations.DeleteModel(
            name='SiteInfo_eu',
        ),
        migrations.DeleteModel(
            name='SiteInfo_ff',
        ),
        migrations.DeleteModel(
            name='SiteInfo_fo',
        ),
        migrations.DeleteModel(
            name='SiteInfo_fy',
        ),
        migrations.DeleteModel(
            name='SiteInfo_gl',
        ),
        migrations.DeleteModel(
            name='SiteInfo_ha',
        ),
        migrations.DeleteModel(
            name='SiteInfo_hr',
        ),
        migrations.DeleteModel(
            name='SiteInfo_ig',
        ),
        migrations.DeleteModel(
            name='SiteInfo_is',
        ),
        migrations.DeleteModel(
            name='SiteInfo_kg',
        ),
        migrations.DeleteModel(
            name='SiteInfo_ki',
        ),
        migrations.DeleteModel(
            name='SiteInfo_la',
        ),
        migrations.DeleteModel(
            name='SiteInfo_lg',
        ),
        migrations.DeleteModel(
            name='SiteInfo_ln',
        ),
        migrations.DeleteModel(
            name='SiteInfo_lt',
        ),
        migrations.DeleteModel(
            name='SiteInfo_lv',
        ),
        migrations.DeleteModel(
            name='SiteInfo_nap',
        ),
        migrations.DeleteModel(
            name='SiteInfo_nso',
        ),
        migrations.DeleteModel(
            name='SiteInfo_ny',
        ),
        migrations.DeleteModel(
            name='SiteInfo_oc',
        ),
        migrations.DeleteModel(
            name='SiteInfo_om',
        ),
        migrations.DeleteModel(
            name='SiteInfo_pms',
        ),
        migrations.DeleteModel(
            name='SiteInfo_rn',
        ),
        migrations.DeleteModel(
            name='SiteInfo_rw',
        ),
        migrations.DeleteModel(
            name='SiteInfo_sc',
        ),
        migrations.DeleteModel(
            name='SiteInfo_scn',
        ),
        migrations.DeleteModel(
            name='SiteInfo_ss',
        ),
        migrations.DeleteModel(
            name='SiteInfo_st',
        ),
        migrations.DeleteModel(
            name='SiteInfo_sw',
        ),
        migrations.DeleteModel(
            name='SiteInfo_tn',
        ),
        migrations.DeleteModel(
            name='SiteInfo_ts',
        ),
        migrations.DeleteModel(
            name='SiteInfo_ve',
        ),
        migrations.DeleteModel(
            name='SiteInfo_vec',
        ),
        migrations.DeleteModel(
            name='SiteInfo_wo',
        ),
        migrations.DeleteModel(
            name='SiteInfo_xh',
        ),
        migrations.DeleteModel(
            name='SiteInfo_yo',
        ),
        migrations.DeleteModel(
            name='SiteInfo_zu',
        ),
    ]
