# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dir', '0031_keywordranking_ca'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AutoComplete_ca',
        ),
        migrations.DeleteModel(
            name='AutoComplete_da',
        ),
        migrations.DeleteModel(
            name='AutoComplete_hr',
        ),
        migrations.DeleteModel(
            name='AutoComplete_no',
        ),
        migrations.DeleteModel(
            name='AutoComplete_ro',
        ),
        migrations.DeleteModel(
            name='AutoComplete_sk',
        ),
        migrations.DeleteModel(
            name='AutoComplete_sl',
        ),
        migrations.DeleteModel(
            name='AutoComplete_sn',
        ),
        migrations.DeleteModel(
            name='AutoComplete_so',
        ),
        migrations.DeleteModel(
            name='IndexTerm_ca',
        ),
        migrations.DeleteModel(
            name='IndexTerm_da',
        ),
        migrations.DeleteModel(
            name='IndexTerm_no',
        ),
        migrations.DeleteModel(
            name='IndexTerm_ro',
        ),
        migrations.DeleteModel(
            name='IndexTerm_sk',
        ),
        migrations.DeleteModel(
            name='IndexTerm_sl',
        ),
        migrations.DeleteModel(
            name='IndexTerm_sn',
        ),
        migrations.DeleteModel(
            name='IndexTerm_so',
        ),
        migrations.DeleteModel(
            name='KeywordRanking_ca',
        ),
        migrations.DeleteModel(
            name='KeywordRanking_da',
        ),
        migrations.DeleteModel(
            name='KeywordRanking_no',
        ),
        migrations.DeleteModel(
            name='KeywordRanking_ro',
        ),
        migrations.DeleteModel(
            name='KeywordRanking_sk',
        ),
        migrations.DeleteModel(
            name='KeywordRanking_sl',
        ),
        migrations.DeleteModel(
            name='KeywordRanking_sn',
        ),
        migrations.DeleteModel(
            name='KeywordRanking_so',
        ),
        migrations.DeleteModel(
            name='PendingIndex_ca',
        ),
        migrations.DeleteModel(
            name='PendingIndex_da',
        ),
        migrations.DeleteModel(
            name='PendingIndex_no',
        ),
        migrations.DeleteModel(
            name='PendingIndex_ro',
        ),
        migrations.DeleteModel(
            name='PendingIndex_sk',
        ),
        migrations.DeleteModel(
            name='PendingIndex_sl',
        ),
        migrations.DeleteModel(
            name='PendingIndex_sn',
        ),
        migrations.DeleteModel(
            name='PendingIndex_so',
        ),
        migrations.DeleteModel(
            name='SiteInfo_ca',
        ),
        migrations.DeleteModel(
            name='SiteInfo_da',
        ),
        migrations.DeleteModel(
            name='SiteInfo_no',
        ),
        migrations.DeleteModel(
            name='SiteInfo_ro',
        ),
        migrations.DeleteModel(
            name='SiteInfo_sk',
        ),
        migrations.DeleteModel(
            name='SiteInfo_sl',
        ),
        migrations.DeleteModel(
            name='SiteInfo_sn',
        ),
        migrations.DeleteModel(
            name='SiteInfo_so',
        ),
    ]
