# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dir', '0043_auto_20190212_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autocomplete',
            name='keywords',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='autocomplete_ca',
            name='keywords',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='autocomplete_cs',
            name='keywords',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='autocomplete_de',
            name='keywords',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='autocomplete_el',
            name='keywords',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='autocomplete_es',
            name='keywords',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='autocomplete_et',
            name='keywords',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='autocomplete_fi',
            name='keywords',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='autocomplete_fr',
            name='keywords',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='autocomplete_hr',
            name='keywords',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='autocomplete_hu',
            name='keywords',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='autocomplete_it',
            name='keywords',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='autocomplete_lt',
            name='keywords',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='autocomplete_lv',
            name='keywords',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='autocomplete_nl',
            name='keywords',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='autocomplete_pl',
            name='keywords',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='autocomplete_pt',
            name='keywords',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='autocomplete_ro',
            name='keywords',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='autocomplete_sl',
            name='keywords',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='autocomplete_sv',
            name='keywords',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='autocomplete_sw',
            name='keywords',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='autocomplete_tr',
            name='keywords',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='domainsearchlog',
            name='keywords',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='ipsearchlog',
            name='keywords',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='searchlog',
            name='keywords',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='searchlog_ca',
            name='keywords',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='searchlog_cs',
            name='keywords',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='searchlog_da',
            name='keywords',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='searchlog_de',
            name='keywords',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='searchlog_el',
            name='keywords',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='searchlog_es',
            name='keywords',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='searchlog_et',
            name='keywords',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='searchlog_fi',
            name='keywords',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='searchlog_fr',
            name='keywords',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='searchlog_ha',
            name='keywords',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='searchlog_hr',
            name='keywords',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='searchlog_hu',
            name='keywords',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='searchlog_is',
            name='keywords',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='searchlog_it',
            name='keywords',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='searchlog_lt',
            name='keywords',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='searchlog_lv',
            name='keywords',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='searchlog_nl',
            name='keywords',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='searchlog_no',
            name='keywords',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='searchlog_pl',
            name='keywords',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='searchlog_pt',
            name='keywords',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='searchlog_ro',
            name='keywords',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='searchlog_rw',
            name='keywords',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='searchlog_sk',
            name='keywords',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='searchlog_sl',
            name='keywords',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='searchlog_sn',
            name='keywords',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='searchlog_so',
            name='keywords',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='searchlog_sv',
            name='keywords',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='searchlog_sw',
            name='keywords',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='searchlog_tr',
            name='keywords',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='searchlog_wo',
            name='keywords',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='searchlog_yo',
            name='keywords',
            field=models.TextField(db_index=True),
        ),
    ]
