# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-26 03:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dir', '0072_auto_20201225_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='filedownload',
            name='date_added',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
