# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-09 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dir', '0074_auto_20210102_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domaininfo',
            name='whois_address',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='domaininfo',
            name='whois_name',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
    ]
