# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-05 02:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210102_1919'),
        ('blog', '0003_auto_20201225_1938'),
    ]

    operations = [
    ]
