# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pendingurl.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pendingurl.proto',
  package='PendingUrl',
  serialized_pb='\n\x10pendingurl.proto\x12\nPendingUrl\"@\n\x03Url\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\x0f\n\x07rooturl\x18\x02 \x01(\t\x12\x0f\n\x07randval\x18\x03 \x01(\x05\x12\n\n\x02id\x18\x04 \x01(\x03\"%\n\x04Urls\x12\x1d\n\x04urls\x18\x01 \x03(\x0b\x32\x0f.PendingUrl.Url\"\x19\n\x06Result\x12\x0f\n\x07success\x18\x01 \x01(\x08\"7\n\x06\x41\x64\x64Url\x12\x0b\n\x03url\x18\x01 \x02(\t\x12\x0f\n\x07rooturl\x18\x02 \x01(\t\x12\x0f\n\x07randval\x18\x03 \x01(\x05\"\x1e\n\rGetRandomUrls\x12\r\n\x05\x63ount\x18\x01 \x02(\x05\"$\n\tDeleteUrl\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0b\n\x03url\x18\x02 \x01(\t\"&\n\x13\x44\x65leteUrlsForDomain\x12\x0f\n\x07rooturl\x18\x01 \x02(\t2\xef\x01\n\rAddUrlService\x12-\n\x03\x41\x64\x64\x12\x12.PendingUrl.AddUrl\x1a\x12.PendingUrl.Result\x12\x33\n\x06\x44\x65lete\x12\x15.PendingUrl.DeleteUrl\x1a\x12.PendingUrl.Result\x12\x43\n\x0cRemoveDomain\x12\x1f.PendingUrl.DeleteUrlsForDomain\x1a\x12.PendingUrl.Result\x12\x35\n\x06Random\x12\x19.PendingUrl.GetRandomUrls\x1a\x10.PendingUrl.Urls')




_URL = _descriptor.Descriptor(
  name='Url',
  full_name='PendingUrl.Url',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='url', full_name='PendingUrl.Url.url', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rooturl', full_name='PendingUrl.Url.rooturl', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='randval', full_name='PendingUrl.Url.randval', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='id', full_name='PendingUrl.Url.id', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=32,
  serialized_end=96,
)


_URLS = _descriptor.Descriptor(
  name='Urls',
  full_name='PendingUrl.Urls',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='urls', full_name='PendingUrl.Urls.urls', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=98,
  serialized_end=135,
)


_RESULT = _descriptor.Descriptor(
  name='Result',
  full_name='PendingUrl.Result',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='PendingUrl.Result.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=137,
  serialized_end=162,
)


_ADDURL = _descriptor.Descriptor(
  name='AddUrl',
  full_name='PendingUrl.AddUrl',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='url', full_name='PendingUrl.AddUrl.url', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rooturl', full_name='PendingUrl.AddUrl.rooturl', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='randval', full_name='PendingUrl.AddUrl.randval', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=164,
  serialized_end=219,
)


_GETRANDOMURLS = _descriptor.Descriptor(
  name='GetRandomUrls',
  full_name='PendingUrl.GetRandomUrls',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='count', full_name='PendingUrl.GetRandomUrls.count', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=221,
  serialized_end=251,
)


_DELETEURL = _descriptor.Descriptor(
  name='DeleteUrl',
  full_name='PendingUrl.DeleteUrl',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='PendingUrl.DeleteUrl.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='url', full_name='PendingUrl.DeleteUrl.url', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=253,
  serialized_end=289,
)


_DELETEURLSFORDOMAIN = _descriptor.Descriptor(
  name='DeleteUrlsForDomain',
  full_name='PendingUrl.DeleteUrlsForDomain',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rooturl', full_name='PendingUrl.DeleteUrlsForDomain.rooturl', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=291,
  serialized_end=329,
)

_URLS.fields_by_name['urls'].message_type = _URL
DESCRIPTOR.message_types_by_name['Url'] = _URL
DESCRIPTOR.message_types_by_name['Urls'] = _URLS
DESCRIPTOR.message_types_by_name['Result'] = _RESULT
DESCRIPTOR.message_types_by_name['AddUrl'] = _ADDURL
DESCRIPTOR.message_types_by_name['GetRandomUrls'] = _GETRANDOMURLS
DESCRIPTOR.message_types_by_name['DeleteUrl'] = _DELETEURL
DESCRIPTOR.message_types_by_name['DeleteUrlsForDomain'] = _DELETEURLSFORDOMAIN

class Url(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _URL

  # @@protoc_insertion_point(class_scope:PendingUrl.Url)

class Urls(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _URLS

  # @@protoc_insertion_point(class_scope:PendingUrl.Urls)

class Result(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _RESULT

  # @@protoc_insertion_point(class_scope:PendingUrl.Result)

class AddUrl(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ADDURL

  # @@protoc_insertion_point(class_scope:PendingUrl.AddUrl)

class GetRandomUrls(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GETRANDOMURLS

  # @@protoc_insertion_point(class_scope:PendingUrl.GetRandomUrls)

class DeleteUrl(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DELETEURL

  # @@protoc_insertion_point(class_scope:PendingUrl.DeleteUrl)

class DeleteUrlsForDomain(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DELETEURLSFORDOMAIN

  # @@protoc_insertion_point(class_scope:PendingUrl.DeleteUrlsForDomain)


# @@protoc_insertion_point(module_scope)
