{% with '2 3 5 7' as numbers %}
{% with numbers.split|random as section %}
{% if section == '1' %}
<!-- Adcash -->
<script data-cfasync="false" type="text/javascript" src="https://www.geniusdexchange.com/a/display.php?r=2266815"></script>
{% elif section == '2' %}
<!-- RevenueHits -->
<script data-cfasync='false' type='text/javascript' src='//p134532.clksite.com/adServe/banners?tid=134532_231433_0'></script>
{% elif section == '3' %}
<!-- Bidvertiser -->
<!-- Begin BidVertiser code -->
<SCRIPT data-cfasync="false" SRC="//bdv.bidvertiser.com/BidVertiser.dbm?pid=724857&bid=1800308" TYPE="text/javascript"></SCRIPT>
<!-- End BidVertiser code -->
{% elif section == '4' %}
<!-- Adsaro -->
<script type='text/javascript' src='https://www.adsaro.net/u/ads/www/delivery/ads.js?zoneid=1886'></script>	
{% elif section == '5' %}
<!-- Adsterra -->
<script type="text/javascript">
	atOptions = {
		'key' : '7cb8fde86d9eb121ba106553cdc48d1a',
		'format' : 'iframe',
		'height' : 90,
		'width' : 728,
		'params' : {}
	};
	document.write('<scr' + 'ipt type="text/javascript" src="http' + (location.protocol === 'https:' ? 's' : '') + '://www.gatetodisplaycontent.com/7cb8fde86d9eb121ba106553cdc48d1a/invoke.js"></scr' + 'ipt>');
</script>
{% elif section == '6' %}
<!-- Media.net -->
<div id="471798331">
    <script type="text/javascript">
        try {
            window._mNHandle.queue.push(function (){
                window._mNDetails.loadTag("471798331", "728x90", "471798331");
            });
        }
        catch (error) {}
    </script>
</div>
{% elif section == '7' %}
<!-- Galaksion -->
<script data-cfasync="false" type="text/javascript" src="//kalespurhoes.com/rI25lARWT64/29680"></script>
{% else %}
<!-- No ads -->
{% endif %}
{% endwith %}
{% endwith %}
