<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-H47FMBKLZM"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-H47FMBKLZM');
</script>
<script>
function ping(id) {
  var req = new XMLHttpRequest();
  req.open("GET", "https://analytics.wbsrch.com/ping/" + id + "/", true);
  req.send();
}
ping(11186);
</script>
