{% load i18n %}<p class="centered hidden-small"><a href="http://mycroftproject.com/search-engines.html?name={% if language_code and language_code != 'en' %}{{ language_code }}.{% endif %}wbsrch.com">Get the WbSrch search plugin</a> for <a href="http://firefox.com">Firefox</a>, Internet Explorer, and other modern browsers, or downnload the <a href="http://wbbrowse.com/">WbBrowse Browser</a>.</p>
<p class="centered"><a href="/ip/">{% trans 'IP Address Info' %}</a> | 
<a href="/changelog/">{% trans "Changelog" %}</a> | <a href="/policy/">{% trans "Inclusion Policy" %}</a> | 
<a href="/philosophy/">{% trans "Philosophy and Goals" %}</a> |  
<a href="/index-stats/">{% trans "Index Statistics" %}</a> | <a href="/howto/">{% trans "How to Use WbSrch" %}</a> |
<a href="/most-linked-to-domains/">Top 100 Most-Linked-To Domains</a> </p>
<p class="centered">
<a href="/articles/">Articles</a> | 
<a href="/terms/">{% trans "Terms of Service" %}</a> | <a href="/privacy/">{% trans "Privacy Policy" %}</a> | 
<a href="/faq/">{% trans "Frequently Asked Questions" %}</a> | <a href="/criteria/">{% trans "Ranking Criteria" %}</a> | 
<a href="/dmca/">{% trans "DMCA and Copyright Policy" %}</a> | <a href="/contact/">{% trans "Contact Information" %}</a></p>
<br/>
<p class="subhead">{% trans "Other languages" %}:</p>
<nav class="language">
<ul name="language" id="language">
<li><a href="https://wbsrch.com/" alt="English" title="English">English (EN)</a></li>
<li><a href="https://ca.wbsrch.com/" alt="Català" title="Català">Català (CA)</a></li>
<li><a href="https://cs.wbsrch.com/" alt="Česká" title="Česká">Česká (CS)</a></li>
<li><a href="https://da.wbsrch.com/" alt="Dansk" title="Dansk">Dansk (DA)</a></li>
<li><a href="https://de.wbsrch.com/" alt="Deutsch" title="Deutsch">Deutsch (DE)</a></li>
<li><a href="https://el.wbsrch.com/" alt="ελληνικά" title="ελληνικά">ελληνικά (EL)</a></li>
<li><a href="https://es.wbsrch.com/" alt="España" title="España">España (ES)</a></li>
<li><a href="https://et.wbsrch.com/" alt="Eesti" title="Eesti">Eesti (ET)</a></li>
<li><a href="https://fi.wbsrch.com/" alt="Suomalais" title="Suomalais">Suomolais (FI)</a></li>
<li><a href="https://fr.wbsrch.com/" alt="Français" title="Français">Français (FR)</a></li>
<li><a href="https://ha.wbsrch.com/" alt="Hausa" title="Hausa">Hausa (HA)</a></li> 
<li><a href="https://hr.wbsrch.com/" alt="Hrvatski" title="Hrvatski">Hrvatski (HR)</a></li>
<li><a href="https://hu.wbsrch.com/" alt="Magyar" title="Magyar">Magyar (HU)</a></li>
<li><a href="https://is.wbsrch.com/" alt="Íslenska" title="Íslenska">Íslenska (IS)</a></li>
<li><a href="https://it.wbsrch.com/" alt="Italiano" title="Italiano">Italiano (IT)</a></li>
<li><a href="https://lt.wbsrch.com/" alt="Lietuvių" title="Lietuvių">Lietuvių (LT)</a></li> 
<li><a href="https://lv.wbsrch.com/" alt="Latviešu" title="Latviešu">Latviešu (LV)</a></li>
<li><a href="https://nl.wbsrch.com/" alt="Nederlands" title="Nederlands">Nederlands (NL)</a></li>
<li><a href="https://no.wbsrch.com/" alt="Norsk" title="Norsk">Norsk (NO)</a></li>
<li><a href="https://pl.wbsrch.com/" alt="Polski" title="Polski">Polski (PL)</a></li>
<li><a href="https://pt.wbsrch.com/" alt="Português" title="Português">Português (PT)</a></li>
<li><a href="https://ro.wbsrch.com/" alt="Română" title="Română">Română (RO)</a></li>
<li><a href="https://rw.wbsrch.com/" alt="Kinyarwanda" title="Kinyarwanda">Kinyarwanda (RW)</a></li> 
<li><a href="https://sk.wbsrch.com/" alt="Slovenský" title="Slovenský">Slovenský (SK)</a></li>
<li><a href="https://sl.wbsrch.com/" alt="Slovenščina" title="Slovenščina">Slovenščina (SL)</a></li>
<li><a href="https://sn.wbsrch.com/" alt="chiShona" title="chiShona">chiShona (SN)</a></li>
<li><a href="https://so.wbsrch.com/" alt="Soomaali" title="Soomaali">Soomaali (SO)</a></li>
<li><a href="https://sv.wbsrch.com/" alt="Svenska" title="Svenska">Svenska (SV)</a></li>
<li><a href="https://sw.wbsrch.com/" alt="Kiswahili" title="Kiswahili">Kiswahili (SW)</a></li>
<li><a href="https://tr.wbsrch.com/" alt="Türkçe" title="Türkçe">Türkçe (TR)</a></li> 
<li><a href="https://wo.wbsrch.com/" alt="Wolof" title="Wolof">Wolof (WO)</a></li>
<li><a href="https://yo.wbsrch.com/" alt="Yorùbá" title="Yorùbá">Yorùbá (YO)</a></li>
</ul>
</nav>
<br/>
