{% load i18n %}
<div class="footer"><p class="centered hidden-small"><a href="http://mycroftproject.com/search-engines.html?name={% if language_code and language_code != 'en' %}{{ language_code }}.{% endif %}wbsrch.com">Get the WbSrch search plugin</a> for <a href="http://firefox.com">Firefox</a>, Internet Explorer, and other modern browsers, or download the <a href="/browser/">WbBrowse Browser</a>.</p>
<p class="centered">
<a href="/ip/">{% trans 'IP Address Info' %}</a> |
<a href="/changelog/">{% trans "Changelog" %}</a> |
<a href="/policy/">{% trans "Inclusion Policy" %}</a> |
<a href="/philosophy/">{% trans "Philosophy and Goals" %}</a> |
<a href="/index-stats/">{% trans "Index Statistics" %}</a> |
<a href="/howto/">{% trans "How to Use WbSrch" %}</a> |
<a href="/most-linked-to-domains/">Top 100 Most-Linked-To Domains</a> |
</p>
<p class="centered">
<a href="/terms/">{% trans "Terms of Service" %}</a> |
<a href="/privacy/">{% trans "Privacy Policy" %}</a> |
<a href="/tld-stats/">{% trans "TLD Stats" %}</a> |
<a href="/faq/">{% trans "Frequently Asked Questions" %}</a> |
<a href="/criteria/">{% trans "Ranking Criteria" %}</a> |
<a href="/dmca/">{% trans "DMCA and Copyright Policy" %}</a> |
<a href="/wbrank/">WbRank</a> |
<a href="/contact/">{% trans "Contact Information" %}</a></p>
<p class="centered">
<a href="https://wbsrch.onfastspring.com">WbSrch Data Shop</a> |
<a href="https://stats.wbsrch.com">WbSrch Stats</a> |
<a href="https://maps.wbsrch.com">WbSrch Maps</a> |
<a href="https://musicsrch.com">MusicSrch Music Search</a>
</p>
</div>
<br/>
