# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dir', '0002_keywordranking_keywordranking_ak_keywordranking_bm_keywordranking_ca_keywordranking_cs_keywordrankin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keywordranking',
            options={},
        ),
        migrations.AlterModelOptions(
            name='keywordranking_ak',
            options={},
        ),
        migrations.AlterModelOptions(
            name='keywordranking_bm',
            options={},
        ),
        migrations.AlterModelOptions(
            name='keywordranking_ca',
            options={},
        ),
        migrations.AlterModelOptions(
            name='keywordranking_cs',
            options={},
        ),
        migrations.AlterModelOptions(
            name='keywordranking_da',
            options={},
        ),
        migrations.AlterModelOptions(
            name='keywordranking_de',
            options={},
        ),
        migrations.AlterModelOptions(
            name='keywordranking_ee',
            options={},
        ),
        migrations.AlterModelOptions(
            name='keywordranking_el',
            options={},
        ),
        migrations.AlterModelOptions(
            name='keywordranking_es',
            options={},
        ),
        migrations.AlterModelOptions(
            name='keywordranking_et',
            options={},
        ),
        migrations.AlterModelOptions(
            name='keywordranking_eu',
            options={},
        ),
        migrations.AlterModelOptions(
            name='keywordranking_ff',
            options={},
        ),
        migrations.AlterModelOptions(
            name='keywordranking_fi',
            options={},
        ),
        migrations.AlterModelOptions(
            name='keywordranking_fo',
            options={},
        ),
        migrations.AlterModelOptions(
            name='keywordranking_fr',
            options={},
        ),
        migrations.AlterModelOptions(
            name='keywordranking_fy',
            options={},
        ),
        migrations.AlterModelOptions(
            name='keywordranking_gl',
            options={},
        ),
        migrations.AlterModelOptions(
            name='keywordranking_ha',
            options={},
        ),
        migrations.AlterModelOptions(
            name='keywordranking_hr',
            options={},
        ),
        migrations.AlterModelOptions(
            name='keywordranking_hu',
            options={},
        ),
        migrations.AlterModelOptions(
            name='keywordranking_ig',
            options={},
        ),
        migrations.AlterModelOptions(
            name='keywordranking_is',
            options={},
        ),
        migrations.AlterModelOptions(
            name='keywordranking_it',
            options={},
        ),
        migrations.AlterModelOptions(
            name='keywordranking_kg',
            options={},
        ),
        migrations.AlterModelOptions(
            name='keywordranking_ki',
            options={},
        ),
        migrations.AlterModelOptions(
            name='keywordranking_lg',
            options={},
        ),
        migrations.AlterModelOptions(
            name='keywordranking_ln',
            options={},
        ),
        migrations.AlterModelOptions(
            name='keywordranking_lt',
            options={},
        ),
        migrations.AlterModelOptions(
            name='keywordranking_lv',
            options={},
        ),
        migrations.AlterModelOptions(
            name='keywordranking_nap',
            options={},
        ),
        migrations.AlterModelOptions(
            name='keywordranking_nl',
            options={},
        ),
        migrations.AlterModelOptions(
            name='keywordranking_no',
            options={},
        ),
        migrations.AlterModelOptions(
            name='keywordranking_nso',
            options={},
        ),
        migrations.AlterModelOptions(
            name='keywordranking_ny',
            options={},
        ),
        migrations.AlterModelOptions(
            name='keywordranking_oc',
            options={},
        ),
        migrations.AlterModelOptions(
            name='keywordranking_om',
            options={},
        ),
        migrations.AlterModelOptions(
            name='keywordranking_pl',
            options={},
        ),
        migrations.AlterModelOptions(
            name='keywordranking_pms',
            options={},
        ),
        migrations.AlterModelOptions(
            name='keywordranking_pt',
            options={},
        ),
        migrations.AlterModelOptions(
            name='keywordranking_rn',
            options={},
        ),
        migrations.AlterModelOptions(
            name='keywordranking_ro',
            options={},
        ),
        migrations.AlterModelOptions(
            name='keywordranking_rw',
            options={},
        ),
        migrations.AlterModelOptions(
            name='keywordranking_sc',
            options={},
        ),
        migrations.AlterModelOptions(
            name='keywordranking_scn',
            options={},
        ),
        migrations.AlterModelOptions(
            name='keywordranking_sk',
            options={},
        ),
        migrations.AlterModelOptions(
            name='keywordranking_sl',
            options={},
        ),
        migrations.AlterModelOptions(
            name='keywordranking_sn',
            options={},
        ),
        migrations.AlterModelOptions(
            name='keywordranking_so',
            options={},
        ),
        migrations.AlterModelOptions(
            name='keywordranking_ss',
            options={},
        ),
        migrations.AlterModelOptions(
            name='keywordranking_st',
            options={},
        ),
        migrations.AlterModelOptions(
            name='keywordranking_sv',
            options={},
        ),
        migrations.AlterModelOptions(
            name='keywordranking_sw',
            options={},
        ),
        migrations.AlterModelOptions(
            name='keywordranking_tn',
            options={},
        ),
        migrations.AlterModelOptions(
            name='keywordranking_tr',
            options={},
        ),
        migrations.AlterModelOptions(
            name='keywordranking_ts',
            options={},
        ),
        migrations.AlterModelOptions(
            name='keywordranking_ve',
            options={},
        ),
        migrations.AlterModelOptions(
            name='keywordranking_vec',
            options={},
        ),
        migrations.AlterModelOptions(
            name='keywordranking_wo',
            options={},
        ),
        migrations.AlterModelOptions(
            name='keywordranking_xh',
            options={},
        ),
        migrations.AlterModelOptions(
            name='keywordranking_yo',
            options={},
        ),
        migrations.AlterModelOptions(
            name='keywordranking_zu',
            options={},
        ),
        migrations.AlterModelOptions(
            name='urllink',
            options={},
        ),
        migrations.RemoveField(
            model_name='keywordranking',
            name='date_indexed',
        ),
        migrations.RemoveField(
            model_name='keywordranking_ak',
            name='date_indexed',
        ),
        migrations.RemoveField(
            model_name='keywordranking_bm',
            name='date_indexed',
        ),
        migrations.RemoveField(
            model_name='keywordranking_ca',
            name='date_indexed',
        ),
        migrations.RemoveField(
            model_name='keywordranking_cs',
            name='date_indexed',
        ),
        migrations.RemoveField(
            model_name='keywordranking_da',
            name='date_indexed',
        ),
        migrations.RemoveField(
            model_name='keywordranking_de',
            name='date_indexed',
        ),
        migrations.RemoveField(
            model_name='keywordranking_ee',
            name='date_indexed',
        ),
        migrations.RemoveField(
            model_name='keywordranking_el',
            name='date_indexed',
        ),
        migrations.RemoveField(
            model_name='keywordranking_es',
            name='date_indexed',
        ),
        migrations.RemoveField(
            model_name='keywordranking_et',
            name='date_indexed',
        ),
        migrations.RemoveField(
            model_name='keywordranking_eu',
            name='date_indexed',
        ),
        migrations.RemoveField(
            model_name='keywordranking_ff',
            name='date_indexed',
        ),
        migrations.RemoveField(
            model_name='keywordranking_fi',
            name='date_indexed',
        ),
        migrations.RemoveField(
            model_name='keywordranking_fo',
            name='date_indexed',
        ),
        migrations.RemoveField(
            model_name='keywordranking_fr',
            name='date_indexed',
        ),
        migrations.RemoveField(
            model_name='keywordranking_fy',
            name='date_indexed',
        ),
        migrations.RemoveField(
            model_name='keywordranking_gl',
            name='date_indexed',
        ),
        migrations.RemoveField(
            model_name='keywordranking_ha',
            name='date_indexed',
        ),
        migrations.RemoveField(
            model_name='keywordranking_hr',
            name='date_indexed',
        ),
        migrations.RemoveField(
            model_name='keywordranking_hu',
            name='date_indexed',
        ),
        migrations.RemoveField(
            model_name='keywordranking_ig',
            name='date_indexed',
        ),
        migrations.RemoveField(
            model_name='keywordranking_is',
            name='date_indexed',
        ),
        migrations.RemoveField(
            model_name='keywordranking_it',
            name='date_indexed',
        ),
        migrations.RemoveField(
            model_name='keywordranking_kg',
            name='date_indexed',
        ),
        migrations.RemoveField(
            model_name='keywordranking_ki',
            name='date_indexed',
        ),
        migrations.RemoveField(
            model_name='keywordranking_lg',
            name='date_indexed',
        ),
        migrations.RemoveField(
            model_name='keywordranking_ln',
            name='date_indexed',
        ),
        migrations.RemoveField(
            model_name='keywordranking_lt',
            name='date_indexed',
        ),
        migrations.RemoveField(
            model_name='keywordranking_lv',
            name='date_indexed',
        ),
        migrations.RemoveField(
            model_name='keywordranking_nap',
            name='date_indexed',
        ),
        migrations.RemoveField(
            model_name='keywordranking_nl',
            name='date_indexed',
        ),
        migrations.RemoveField(
            model_name='keywordranking_no',
            name='date_indexed',
        ),
        migrations.RemoveField(
            model_name='keywordranking_nso',
            name='date_indexed',
        ),
        migrations.RemoveField(
            model_name='keywordranking_ny',
            name='date_indexed',
        ),
        migrations.RemoveField(
            model_name='keywordranking_oc',
            name='date_indexed',
        ),
        migrations.RemoveField(
            model_name='keywordranking_om',
            name='date_indexed',
        ),
        migrations.RemoveField(
            model_name='keywordranking_pl',
            name='date_indexed',
        ),
        migrations.RemoveField(
            model_name='keywordranking_pms',
            name='date_indexed',
        ),
        migrations.RemoveField(
            model_name='keywordranking_pt',
            name='date_indexed',
        ),
        migrations.RemoveField(
            model_name='keywordranking_rn',
            name='date_indexed',
        ),
        migrations.RemoveField(
            model_name='keywordranking_ro',
            name='date_indexed',
        ),
        migrations.RemoveField(
            model_name='keywordranking_rw',
            name='date_indexed',
        ),
        migrations.RemoveField(
            model_name='keywordranking_sc',
            name='date_indexed',
        ),
        migrations.RemoveField(
            model_name='keywordranking_scn',
            name='date_indexed',
        ),
        migrations.RemoveField(
            model_name='keywordranking_sk',
            name='date_indexed',
        ),
        migrations.RemoveField(
            model_name='keywordranking_sl',
            name='date_indexed',
        ),
        migrations.RemoveField(
            model_name='keywordranking_sn',
            name='date_indexed',
        ),
        migrations.RemoveField(
            model_name='keywordranking_so',
            name='date_indexed',
        ),
        migrations.RemoveField(
            model_name='keywordranking_ss',
            name='date_indexed',
        ),
        migrations.RemoveField(
            model_name='keywordranking_st',
            name='date_indexed',
        ),
        migrations.RemoveField(
            model_name='keywordranking_sv',
            name='date_indexed',
        ),
        migrations.RemoveField(
            model_name='keywordranking_sw',
            name='date_indexed',
        ),
        migrations.RemoveField(
            model_name='keywordranking_tn',
            name='date_indexed',
        ),
        migrations.RemoveField(
            model_name='keywordranking_tr',
            name='date_indexed',
        ),
        migrations.RemoveField(
            model_name='keywordranking_ts',
            name='date_indexed',
        ),
        migrations.RemoveField(
            model_name='keywordranking_ve',
            name='date_indexed',
        ),
        migrations.RemoveField(
            model_name='keywordranking_vec',
            name='date_indexed',
        ),
        migrations.RemoveField(
            model_name='keywordranking_wo',
            name='date_indexed',
        ),
        migrations.RemoveField(
            model_name='keywordranking_xh',
            name='date_indexed',
        ),
        migrations.RemoveField(
            model_name='keywordranking_yo',
            name='date_indexed',
        ),
        migrations.RemoveField(
            model_name='keywordranking_zu',
            name='date_indexed',
        ),
    ]
