# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dir', '0003_auto_20150715_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywordranking',
            name='keywords',
            field=models.CharField(max_length=240, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='keywordranking_ak',
            name='keywords',
            field=models.CharField(max_length=240, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='keywordranking_bm',
            name='keywords',
            field=models.CharField(max_length=240, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='keywordranking_ca',
            name='keywords',
            field=models.CharField(max_length=240, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='keywordranking_cs',
            name='keywords',
            field=models.CharField(max_length=240, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='keywordranking_da',
            name='keywords',
            field=models.CharField(max_length=240, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='keywordranking_de',
            name='keywords',
            field=models.CharField(max_length=240, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='keywordranking_ee',
            name='keywords',
            field=models.CharField(max_length=240, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='keywordranking_el',
            name='keywords',
            field=models.CharField(max_length=240, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='keywordranking_es',
            name='keywords',
            field=models.CharField(max_length=240, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='keywordranking_et',
            name='keywords',
            field=models.CharField(max_length=240, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='keywordranking_eu',
            name='keywords',
            field=models.CharField(max_length=240, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='keywordranking_ff',
            name='keywords',
            field=models.CharField(max_length=240, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='keywordranking_fi',
            name='keywords',
            field=models.CharField(max_length=240, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='keywordranking_fo',
            name='keywords',
            field=models.CharField(max_length=240, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='keywordranking_fr',
            name='keywords',
            field=models.CharField(max_length=240, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='keywordranking_fy',
            name='keywords',
            field=models.CharField(max_length=240, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='keywordranking_gl',
            name='keywords',
            field=models.CharField(max_length=240, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='keywordranking_ha',
            name='keywords',
            field=models.CharField(max_length=240, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='keywordranking_hr',
            name='keywords',
            field=models.CharField(max_length=240, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='keywordranking_hu',
            name='keywords',
            field=models.CharField(max_length=240, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='keywordranking_ig',
            name='keywords',
            field=models.CharField(max_length=240, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='keywordranking_is',
            name='keywords',
            field=models.CharField(max_length=240, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='keywordranking_it',
            name='keywords',
            field=models.CharField(max_length=240, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='keywordranking_kg',
            name='keywords',
            field=models.CharField(max_length=240, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='keywordranking_ki',
            name='keywords',
            field=models.CharField(max_length=240, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='keywordranking_lg',
            name='keywords',
            field=models.CharField(max_length=240, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='keywordranking_ln',
            name='keywords',
            field=models.CharField(max_length=240, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='keywordranking_lt',
            name='keywords',
            field=models.CharField(max_length=240, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='keywordranking_lv',
            name='keywords',
            field=models.CharField(max_length=240, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='keywordranking_nap',
            name='keywords',
            field=models.CharField(max_length=240, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='keywordranking_nl',
            name='keywords',
            field=models.CharField(max_length=240, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='keywordranking_no',
            name='keywords',
            field=models.CharField(max_length=240, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='keywordranking_nso',
            name='keywords',
            field=models.CharField(max_length=240, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='keywordranking_ny',
            name='keywords',
            field=models.CharField(max_length=240, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='keywordranking_oc',
            name='keywords',
            field=models.CharField(max_length=240, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='keywordranking_om',
            name='keywords',
            field=models.CharField(max_length=240, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='keywordranking_pl',
            name='keywords',
            field=models.CharField(max_length=240, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='keywordranking_pms',
            name='keywords',
            field=models.CharField(max_length=240, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='keywordranking_pt',
            name='keywords',
            field=models.CharField(max_length=240, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='keywordranking_rn',
            name='keywords',
            field=models.CharField(max_length=240, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='keywordranking_ro',
            name='keywords',
            field=models.CharField(max_length=240, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='keywordranking_rw',
            name='keywords',
            field=models.CharField(max_length=240, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='keywordranking_sc',
            name='keywords',
            field=models.CharField(max_length=240, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='keywordranking_scn',
            name='keywords',
            field=models.CharField(max_length=240, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='keywordranking_sk',
            name='keywords',
            field=models.CharField(max_length=240, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='keywordranking_sl',
            name='keywords',
            field=models.CharField(max_length=240, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='keywordranking_sn',
            name='keywords',
            field=models.CharField(max_length=240, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='keywordranking_so',
            name='keywords',
            field=models.CharField(max_length=240, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='keywordranking_ss',
            name='keywords',
            field=models.CharField(max_length=240, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='keywordranking_st',
            name='keywords',
            field=models.CharField(max_length=240, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='keywordranking_sv',
            name='keywords',
            field=models.CharField(max_length=240, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='keywordranking_sw',
            name='keywords',
            field=models.CharField(max_length=240, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='keywordranking_tn',
            name='keywords',
            field=models.CharField(max_length=240, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='keywordranking_tr',
            name='keywords',
            field=models.CharField(max_length=240, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='keywordranking_ts',
            name='keywords',
            field=models.CharField(max_length=240, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='keywordranking_ve',
            name='keywords',
            field=models.CharField(max_length=240, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='keywordranking_vec',
            name='keywords',
            field=models.CharField(max_length=240, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='keywordranking_wo',
            name='keywords',
            field=models.CharField(max_length=240, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='keywordranking_xh',
            name='keywords',
            field=models.CharField(max_length=240, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='keywordranking_yo',
            name='keywords',
            field=models.CharField(max_length=240, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='keywordranking_zu',
            name='keywords',
            field=models.CharField(max_length=240, db_index=True),
            preserve_default=True,
        ),
    ]
