CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE INDEX dir_siteinfo_zu_pagetitle_gin ON dir_siteinfo_zu USING gin(pagetitle gin_trgm_ops);
CREATE INDEX dir_siteinfo_zu_pagedescription_gin ON dir_siteinfo_zu USING gin(pagedescription gin_trgm_ops);
CREATE INDEX dir_siteinfo_zu_pagekeywords_gin ON dir_siteinfo_zu USING gin(pagekeywords gin_trgm_ops);
CREATE INDEX dir_siteinfo_zu_pagefirstheadtag_gin ON dir_siteinfo_zu USING gin(pagefirstheadtag gin_trgm_ops);
CREATE INDEX dir_siteinfo_zu_pagefirsth2tag_gin ON dir_siteinfo_zu USING gin(pagefirsth2tag gin_trgm_ops);
CREATE INDEX dir_siteinfo_zu_pagefirsth3tag_gin ON dir_siteinfo_zu USING gin(pagefirsth3tag gin_trgm_ops);
CREATE INDEX dir_siteinfo_zu_pagetext_gin ON dir_siteinfo_zu USING gin(pagetext gin_trgm_ops);
CREATE INDEX dir_siteinfo_zu_url_gin ON dir_siteinfo_zu USING gin(url gin_trgm_ops);
CREATE INDEX dir_siteinfo_zu_rooturl_gin ON dir_siteinfo_zu USING gin(rooturl gin_trgm_ops);
