CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE INDEX dir_siteinfo_sn_pagetitle_gin ON dir_siteinfo_sn USING gin(pagetitle gin_trgm_ops);
CREATE INDEX dir_siteinfo_sn_pagedescription_gin ON dir_siteinfo_sn USING gin(pagedescription gin_trgm_ops);
CREATE INDEX dir_siteinfo_sn_pagekeywords_gin ON dir_siteinfo_sn USING gin(pagekeywords gin_trgm_ops);
CREATE INDEX dir_siteinfo_sn_pagefirstheadtag_gin ON dir_siteinfo_sn USING gin(pagefirstheadtag gin_trgm_ops);
CREATE INDEX dir_siteinfo_sn_pagefirsth2tag_gin ON dir_siteinfo_sn USING gin(pagefirsth2tag gin_trgm_ops);
CREATE INDEX dir_siteinfo_sn_pagefirsth3tag_gin ON dir_siteinfo_sn USING gin(pagefirsth3tag gin_trgm_ops);
CREATE INDEX dir_siteinfo_sn_pagetext_gin ON dir_siteinfo_sn USING gin(pagetext gin_trgm_ops);
CREATE INDEX dir_siteinfo_sn_url_gin ON dir_siteinfo_sn USING gin(url gin_trgm_ops);
CREATE INDEX dir_siteinfo_sn_rooturl_gin ON dir_siteinfo_sn USING gin(rooturl gin_trgm_ops);
