CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE INDEX dir_siteinfo_rw_pagetitle_gin ON dir_siteinfo_rw USING gin(pagetitle gin_trgm_ops);
CREATE INDEX dir_siteinfo_rw_pagedescription_gin ON dir_siteinfo_rw USING gin(pagedescription gin_trgm_ops);
CREATE INDEX dir_siteinfo_rw_pagekeywords_gin ON dir_siteinfo_rw USING gin(pagekeywords gin_trgm_ops);
CREATE INDEX dir_siteinfo_rw_pagefirstheadtag_gin ON dir_siteinfo_rw USING gin(pagefirstheadtag gin_trgm_ops);
CREATE INDEX dir_siteinfo_rw_pagefirsth2tag_gin ON dir_siteinfo_rw USING gin(pagefirsth2tag gin_trgm_ops);
CREATE INDEX dir_siteinfo_rw_pagefirsth3tag_gin ON dir_siteinfo_rw USING gin(pagefirsth3tag gin_trgm_ops);
CREATE INDEX dir_siteinfo_rw_pagetext_gin ON dir_siteinfo_rw USING gin(pagetext gin_trgm_ops);
CREATE INDEX dir_siteinfo_rw_url_gin ON dir_siteinfo_rw USING gin(url gin_trgm_ops);
CREATE INDEX dir_siteinfo_rw_rooturl_gin ON dir_siteinfo_rw USING gin(rooturl gin_trgm_ops);
