CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE INDEX dir_siteinfo_so_pagetitle_gin ON dir_siteinfo_so USING gin(pagetitle gin_trgm_ops);
CREATE INDEX dir_siteinfo_so_pagedescription_gin ON dir_siteinfo_so USING gin(pagedescription gin_trgm_ops);
CREATE INDEX dir_siteinfo_so_pagekeywords_gin ON dir_siteinfo_so USING gin(pagekeywords gin_trgm_ops);
CREATE INDEX dir_siteinfo_so_pagefirstheadtag_gin ON dir_siteinfo_so USING gin(pagefirstheadtag gin_trgm_ops);
CREATE INDEX dir_siteinfo_so_pagefirsth2tag_gin ON dir_siteinfo_so USING gin(pagefirsth2tag gin_trgm_ops);
CREATE INDEX dir_siteinfo_so_pagefirsth3tag_gin ON dir_siteinfo_so USING gin(pagefirsth3tag gin_trgm_ops);
CREATE INDEX dir_siteinfo_so_pagetext_gin ON dir_siteinfo_so USING gin(pagetext gin_trgm_ops);
CREATE INDEX dir_siteinfo_so_url_gin ON dir_siteinfo_so USING gin(url gin_trgm_ops);
CREATE INDEX dir_siteinfo_so_rooturl_gin ON dir_siteinfo_so USING gin(rooturl gin_trgm_ops);
CREATE INDEX dir_siteinfo_so_rooturl_btree ON dir_siteinfo_so (rooturl);
